### PR TITLE
Fixes #2486:  adding optional custom arguments to salt-call

### LINKED ISSUE #2485: amazon-ebs builder: Packer does not automatically choose available AWS availability zones
I did not specify `availability_zone` in my `amazon-ebs` builder configuration. I received:

```
Build 'amazon-ebs' errored: Error launching source instance: InsufficientInstanceCapacity: We currently do not have sufficient m4.large capacity in the Availability Zone you requested (us-east-1a). Our system will be working on provisioning additional capacity. You can currently get m4.large capacity by not specifying an Availability Zone in your request or choosing us-east-1d, us-east-1e, us-east-1c.
    status code: 500, request id: []

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error launching source instance: InsufficientInstanceCapacity: We currently do not have sufficient m4.large capacity in the Availability Zone you requested (us-east-1a). Our system will be working on provisioning additional capacity. You can currently get m4.large capacity by not specifying an Availability Zone in your request or choosing us-east-1d, us-east-1e, us-east-1c.
    status code: 500, request id: []
```

Packer [amazon-ebs builder documentation](https://www.packer.io/docs/builders/amazon-ebs.html) states that Packer will let Amazon auto-assign the availability zone:

> `availability_zone` (string) - Destination availability zone to launch instance in. Leave this empty to allow Amazon to auto-assign.`

However, as implied by the above errors, Packer appears to have requested `us-east-1a` explicitly.

Packer version: **0.8.1**

### LINKED ISSUE #2486: Unable to remove --retcode-passthrough from salt-call in salt-masterless provisioner
It would nice if there was a way to remove that option since there are cases like mine where some salt-states will fail, but I don't want the entire build to fail because of it.

It seems like the best way to implement this would be to have an option in that provisioner that allows you send custom arguments to the salt call that is performed, similar to the way that arguments can be passed to the salt-bootstrap script.

I might be able to put some work in on this, but if anyone else can implement it quickly it would be greatly appreciated.

### PR DESCRIPTION
**Pull request by david-thorman**
Adding configuration parameter `salt_call_args` to customize how salt-call state.highstate is called on the box being provisioned, backwards compatible default added.

### CODE REVIEW

**Comment by cbednarski** [comment]
Thanks for the PR! This looks great. There's an established pattern to use "execute command" to specify the default behavior for the provisioner. SSH and puppet use this technique. Can you mimic that style for naming in your PR?

Example [docs](https://packer.io/docs/provisioners/puppet-masterless.html) and [code](https://github.com/mitchellh/packer/blob/master/provisioner/puppet-masterless/provisioner.go#L82-L90), from puppet masterless.

Btw, it's not necessary to add interpolation -- I'm mainly concerned about the naming so it's consistent across plugins.

Also, unit tests would be a bonus. You don't have to write these, but it will help me merge this more quickly. If you have trouble writing the tests let me know, or if you can't I will get around to it eventually.

Thanks!

**Comment by david-thorman** [comment]
@cbednarski I have updated the pull request. There was a conflict with some upstream changes, not sure if my change is the best resolution. It seems like it would be better to do some of the string interpolation so that way the execute command could use the remote pillar/state folder configuration options. Not sure how the other provisioners handle it, though I can do a little more reading. I am not quite sure how to do the unit tests, but I might be able to get around to them soon.

**Comment by david-thorman** [comment]
Actually after looking at the puppet provisioner, it doesn't seem too complex to do the string interpolation.

**Comment by rickard-von-essen** [comment]
This might conflict with #3776

**Comment by mwhooker** [comment]
This is great but needs a rebase, and not sure if it's actively being worked on. Happy to review if you submit a new PR

**Comment by david-thorman** [comment]
I haven't put any more work into this, but it seems like #4158  covers this functionality. Thanks for your time.

**Pull request closed without merging**
