### PR TITLE
providing documentation for solving issue #3586

### LINKED ISSUE #3586: qemu: Error processing QemuArggs: No version found
Failed to build qemu template on Windows 7 machine: Packer could not read qemu version.

qemu stores all CLI commands outputs into a log file: stdout.txt and it seems packer is trying to read that from a console/variable. 

- Packer Version: 0.10.1
- Host platform: Windows 7 64 bits
- Debug log file: [log](https://gist.github.com/lucassrg/7f05629aab9acd721460d5e5e2021040) 

- Qemu emulator: 2.6.50

### PR DESCRIPTION
**Pull request by lfarnell**
Providing some documentation on getting QEMU on Windows to work with Packer.
Closes #3586

### CODE REVIEW

**Comment by ryanmaclean** [comment]
Unfortunately the 2.5 version seems problematic on Windows 10 Fast Ring, whereas the https://qemu.weilnetz.de version does in fact work (though does not provide a version in the way Packer expects it).

**Comment by ryanmaclean** [comment]
In case this is ever found as a result of a search for the same problem: https://qemu.weilnetz.de/FAQ details that the env var `SDL_STDIO_REDIRECT` can be set in order to retain the output to command line for qemu version requirements on the Windows build.

**Comment by lfarnell** [comment]
@ryanmaclean Just updated the docs if you want to take a look.

**Comment by ryanmaclean** [comment]
Sweet, thanks! I know it's a bit of an odd platform combo, but I happen to be doing some work with this at the moment 😂

**Comment by ryanmaclean** [comment]
@lfarnell: on my end, I needed to do `SDL_STDIO_REDIRECT=0` in order to get this working. Did `=1` work on your end?

**Comment by lfarnell** [comment]
it was a typo on my end. Should be good now.

**Pull request merged**
