### PR TITLE
Manifest post processor

### PR DESCRIPTION
**Pull request by cbednarski**
This is a new post-processor that writes metadata about packer's output artifacts data to a JSON file.

- [x] Still need to fix `Post-processor failed: open packer-manifest.json: no such file or directory`
- [ ] Add some tests
- [ ] Add file size

/cc @grubernaut

### CODE REVIEW

**Comment by vtolstov** [comment]
usefu feature, i have metadata post processor =) that works like this, but also it write file size for each artifact.
Do you want to add this feature ?
This is needed in my case - i'm use compressed image to intall to raw disk and i need to know original size to write proper progress bar =)

**Comment by grubernaut** [comment]
This fixes the `Post-processor failed: open packer-manifest.json: no such file or directory` error on initial read: 
```
diff --git a/post-processor/manifest/post-processor.go b/post-processor/manifest/post-processor.go
index 69fb108..503885d 100644
--- a/post-processor/manifest/post-processor.go
+++ b/post-processor/manifest/post-processor.go
@@ -89,8 +89,10 @@ func (p *PostProcessor) PostProcess(ui packer.Ui, source packer.Artifact) (packe
        //
        // Read the current manifest file from disk
        contents := []byte{}
-       if contents, err = ioutil.ReadFile(p.config.Filename); err != nil && !os.IsNotExist(err) {
-               return source, true, fmt.Errorf("Unable to open %s for reading: %s", p.config.Filename, err)
+       if _, err := os.Stat(p.config.Filename); !os.IsNotExist(err) {
+               if contents, err = ioutil.ReadFile(p.config.Filename); err != nil {
+                       return source, true, fmt.Errorf("Unable to open %s for reading: %s", p.config.Filename, err)
+               }
        }
 
        // Parse the manifest file JSON, if we have one
```

**Comment by cbednarski** [comment]
@vtolstov Sure, I can add file size. I will do bytes as an integer. Does that work for you?

> Post-processor failed: open packer-manifest.json: no such file or directory

@grubernaut  The problem was that I returned `err` instead of `nil` at the end. Fixed in https://github.com/mitchellh/packer/pull/3651/commits/19057028cfc2392a886b068d7bd779b5713a3873

**Comment by vtolstov** [comment]
@cbednarski thanks, so in this case after each post-processor i can add manifest post processor and write info about previous step?

**Comment by cbednarski** [comment]
@vtolstov Correct. Manifest accepts any type of artifact, collects metadata, and passes the original artifact through to the next post-processor. So for example you can do:

    qemu -> manifest -> compress

And `compress` will compress the QEMU file, _not_ the `packer-manifest.json`.

**Comment by vtolstov** [comment]
thanks!

**Comment by cbednarski** [comment]
Will follow up on this for the other two checklist items.

**Comment by vtolstov** [comment]
i'm waiting for file size =))

**Comment by vtolstov** [comment]
@cbednarski any news?

**Comment by vtolstov** [comment]
i can create pr, if you suggest json schema for file size representation

**Pull request merged**
