### PR TITLE
Updated how vmx entries are handled

### PR DESCRIPTION
**Pull request by marc-ta**
VMWare added the virtualSSD flag to disks, but they made it case sensitive, so i removed the ToLower. At the same time, it also requires no quotes around the value, so i added an array to look for that (and any future cases where they do this)

The key was created like this: `sata0:0.virtualssd = "1"`
but must be like this to work: `sata0:0.virtualSSD = 1`

### CODE REVIEW

**Comment by dhekimian** [comment]
@mitchellh This goes with https://github.com/mitchellh/packer/pull/2254 (already merged in 0.8.0).

**Comment by marc-ta** [comment]
Testing a bug fix, introduced by not lowercasing the vmx entries. Another commit to follow.

**Comment by dhekimian** [comment]
@mitchellh @cbednarski What's necessary to get this committed? #2254 (already merged in 0.8.0) introduced a bug that is fixed by this PR.

**Comment by cbednarski** [comment]
@dhekimian Thanks for the ping. This LGTM!

**Pull request merged**
