### PR TITLE
Generate key files for Ansible provisioner

### PR DESCRIPTION
**Pull request by mtb-xt**
In #1969 @dkhenry made changes that allowed to generate ssh keys for Ansible provisioner on the fly, but they weren't included. 
I've tested the changes made in dkhenry/packer@124f650f4fcaf262c2358e536cad57ed63319640, they are working and they make life a lot easier without the need to manually generate those keys 
(Packer already generates its own keys during the build, so this is not a big security hole)

Can this be added to the 0.9 release?

### CODE REVIEW

**Comment by cbednarski** [comment]
Looks great, thanks!

**Comment by rickard-von-essen** [comment]
This is great, I was just about to implement something similar.

**Comment by dkhenry** [comment]
Awesome.

**Comment by bhcleek** [comment]
I'm really happy to see this, too. Great job, @dkhenry !

**Pull request merged**
