### PR TITLE
Optimize Packer document view for iPad portrait mode

### PR DESCRIPTION
**Pull request by inntran**
Changes in this pull request:
- reduced margin, padding, line-height of several elements
- created iPad specific media selector
- removed unnecessary spaces around headers and list elements
- reduced code font size to 12px
- removed unnecessary optimization of page footer for tablets

I've found that although Packer's document is using Bootstrap framework, it's not tablet friendly. So here's my attempt to make it display better on iPad (768x1024).

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Could you add two screenshots, one with and one without you change?

**Comment by inntran** [comment]
## Without change
### Page header navigation
img_0037
### End of left navigation sidebar
img_0038
### Beginning of document content
img_0039
### Footer mixed with content
img_0040
### End of page
img_0041

## With changes
### Beginning of content
img_0042
### End of navigation sidebar
img_0043
### Page footer
img_0045

**Comment by inntran** [comment]
@rickard-von-essen do these screenshots look good to you? If you think it's too compact compared to original one, I can give it more margin.

**Comment by rickard-von-essen** [comment]
From the screenshots it looks great! I don't have access to an iPad for testing. I'll merge it within some days if no one objects. 

The website is deployed when a release is made.

**Pull request merged**
