### PR TITLE
Parallels Desktop 11: verify correct edition and enable headless mode

### PR DESCRIPTION
**Pull request by rickard-von-essen**
This improves the support for Parallels Desktop for Mac 11 support by:
- Verify you are not trying to build with _Standard Edition_ which lacks necessary command line support.
- Enable ```headless``` mode for PD 11 (which was previously ignored).

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
@legal90 could you review this, please.

**Comment by legal90** [comment]
It looks good to me, but I also think that "headless" mode can be enabled by default for PD 11.
And even more, it could be done just by adding `[]string{"set", vmName, "--startup-view", "headless"}`
to `SetDefaultConfiguration` func for PD11 structure.
Then we don't need to check `driver.SupportHeadless()` and `s.Headless`. 

Unlikely Virtualbox, headless mode in Parallels Desktop is more convenient, so user can always get a VM window by clicking VM name in the Parallels Desktop Control Center (VM list in GUI).

**Comment by rickard-von-essen** [comment]
@legal90 You are correct, I changed the code to always use headless on PD11 and to remove the ```headless``` config option for parallels builder. See 83980d2

**Comment by legal90** [comment]
Great! LGTM

P.s. "Fixer" is a great thing we should use it to handle other deprecated options as well (like `guest_os_distribution ` and  `parallels_tools_host_path `)

**Pull request merged**
