### PR TITLE
Add dry-run to Packer

### PR DESCRIPTION
**Pull request by ColinHebert**
Hey guys, I've tried to add dry-run mode to packer, should do a lot of awesome stuff :)

### CODE REVIEW

**Comment by ColinHebert** [comment]
@sethvargo @mitchellh Any news?

**Comment by ColinHebert** [comment]
@sethvargo Happy to get any feedback on this issue.

**Comment by ColinHebert** [comment]
It's been three months, is there anything I can do to help speeding up the process?

**Comment by mitchellh** [comment]
Hey, sorry, I'm not actually a big fan of this since I'm not sure what value it brings. I can see the value for a `--delete-artifact` option which just deletes the artifact after it is created, but I don't see a lot of use for this, since its so logic dependent on what a builder does with this flag. And, the implementation for that would look quite a bit different.

Sorry for the long delay, I should've answered a long time ago.

**Comment by dnk8n** [comment]
I would love to be able to create a docker image from within my own vpc, but kicked off by a CI tool (outside my VPC).

The workflow I envisage is:

1.) A push to a branch triggers some automation within a CI tool (think bitbucket pipelines for example).
2.) This CI tool securely has access to my VPC credentials and runs automation

Option 1 (hypothetical):
3.1) This automation runs a packer build process which spins up an instance (with docker and packer installed) in my VPC
4.1) The packer build process runs a 'nested packer' build process within the instance which results in a docker image which gets pushed to my VPC's registry, as well as dockerhub. It also results in some artifacts which can be hosted in my VPC or hosted elsewhere.
5.1) Once the outer packer scripts are run, the instance is no longer required (and an AMI does not need to be created) so it can just be trashed

Option 2 (exists):

3.2) Use terraform apply to spin up an EC2 instance (with docker and packer installed)
4.2) Use a null resource to run packer build commands against the instance (same as 4.1 above)
5.2) Use terraform destroy to get rid of the temporary infrastructure.


Is there another way I don't know about to have an external CI tool run docker image building processes on infrastructure within my own VPC? Why I would want this, often the infrastructure does not have the specs I require in order to run the docker image build processes I require (runs out of memory, etc) and I would like the ability to choose my own infrastructure.

I think option 1 would result in a more eloquent solution than the existing option 2.

Thoughts?

**Comment by SwampDragons** [comment]
@dnk8n this issue was closed 3 years ago, and I doubt many people are still following it. You're more likely to get the conversation you want from the mailing list: https://groups.google.com/forum/#!forum/packer-tool

**Pull request closed without merging**
