### PR TITLE
builder/amazon: crash on tagging snapshot when snapshot_tags is unset

### LINKED ISSUE #4238: amazon: master crash on snapshot tags.
If `tags` are defined but no `snapshot_tags` packer crashes. I'll try to a repo soon.

### PR DESCRIPTION
**Pull request by rickard-von-essen**
Closes #4238

### CODE REVIEW

**Comment by mwhooker** [comment]
👍

**Comment by artburkart** [comment]
Ewf - sorry! I missed it.

**Comment by artburkart** [comment]
If I had ran the entire acceptance suite, would I have caught this? If so, I'll definitely do my due diligence next time.

**Comment by rickard-von-essen** [comment]
I also missed it during my testing. Typical happy path testing only.

**Pull request merged**
