### PR TITLE
Make DigitalOcean artifact ID match AWS format

### PR DESCRIPTION
**Pull request by lolindrath**
The Vagrant post processor expects the DO artifact ID to look like an
AWS artifact ID (region_id:snapshot_id). This commit makes the DO
artifact Id() function output this format. Addresses Issue #2491.

### CODE REVIEW

**Comment by lolindrath** [comment]
This is my first PR for packer so go easy ;) I also don't have a high level idea of what other ramifications changing the format of the Digital Ocean Artifact ID might cause either. Let me know how I can improve it.

**Comment by markpeek** [comment]
This change reverses commit https://github.com/mitchellh/packer/commit/3d6865fafc394e888dea07abd7f2afcc524ecee7. I agree the current artifact id and the post-processor need to be synced. But the primary question is what is the right format for the artifact id for DO and then make sure the two can interoperate. Adding @chuyeow and @pearkes to see if they have opinions on this change.

Note: I noticed some existing commits are included in this change. I'm not quite sure how those were merged into your commit. The main change is https://github.com/lolindrath/packer/commit/cda8fc3d278bf2d554e200635a578960066fd52b.

**Comment by chuyeow** [comment]
@markpeek thanks for notifying me about this change. I have no problems with it being changed but the last time I changed the artifact ID in 3d6865f, stuff broke for other people since it wasn't covered by any tests, so do bear  in mind (and would be nice to make a mention of it in the changelog for people upgrading).

**Comment by pearkes** [comment]
@markpeek Yes unfortunately I think this may in fact cause issues upstream, so we need to tread carefully. Going to add @clstokes from our end to help determine how this might effect folks.

Overall I agree with the format changing to this, but am wary to break something without understanding the scope of the breakage.

**Comment by clstokes** [comment]
I've built this Packer branch locally and tested it with Terraform's [atlas_artifact](https://terraform.io/docs/providers/atlas/r/artifact.html) resource both with brand new artifacts and "upgrading" a pre-existing artifact that was built with an older version of Packer and both situations worked fine.

If someone can share what issues were encountered previously I can try some more scenarios. Otherwise, it seems this change works fine in terms of Packer and Terraform working together.

/cc @pearkes

**Comment by pearkes** [comment]
@clstokes Great! Thanks!

**Comment by andyfowler** [comment]
@lolindrath it sounds like you've got the :+1: from the group on getting this PR merged in. I encountered the issue myself, and it seems like Packer + DO + Vagrant is currently broken without this. Are you up for rebasing this PR so it's mergeable?

**Comment by markpeek** [comment]
Merged via #2934

**Pull request closed without merging**
