### PR TITLE
SCSI Support in virtualbox driver

### PR DESCRIPTION
**Pull request by daniellockard**
I'm working on a packer plugin that needs SCSI support for maximum performance, this seems to work for me. I welcome any feedback.

### CODE REVIEW

**Comment by rasa** [comment]
LGTM. Thanks!

**Comment by megvt08** [comment]
This is what i needed really and thank you so much. now how can i use this?

**Comment by daniellockard** [comment]
if you pull and compiled packer yourself you should be able to specify scsi instead of ide or sata in hard_drive_interface.

**Comment by megvt08** [comment]
Thank you so much for quick response, My issue was i have already done this but i had an issue with compiling and also i really preferred if this was part of the packer package rather than a custom hack. 
I have also made add the following and not sure if its actually necessary
File : ``` builder/virtualbox/iso/builder_test.go```
``` 
263   // SCSI Test with a good
264   config["hard_drive_interface"] = "scsi"
265   b = Builder{}
266   warns, err = b.Prepare(config)
267   if len(warns) > 0 {
268     t.Fatalf("bad: %#v", warns)
269   }
270   if err != nil {
271     t.Fatalf("should not have error: %s", err)
272   }
```

**Comment by daniellockard** [comment]
I'm sure it will be in a packer release soon. I don't have any control over that :) What issue did you have compiling?

**Comment by megvt08** [comment]
it was GOX :) and it was me missing some stuff (RTFM)

**Pull request merged**
