### PR TITLE
Make PackerBuildName and PackerBuilderType available as Facts during a m...

### PR DESCRIPTION
**Pull request by danzilio**
...asterless run similar to the way we do with the Shell provisioner.

### CODE REVIEW

**Comment by danzilio** [comment]
Hmmm...I can't seem to recreate this failure locally...PEBKAC?

**Comment by sethvargo** [comment]
This seems pretty reasonable to me, and thank you for update the docs too :smile:. Would you mind doing a rebase and seeing if that fixes the build failure?

It would be great if you could add a test for this, but I know that might not be the easiest with all the moving parts.

**Comment by danzilio** [comment]
Looks like a rebase fixed the build failure!! I can definitely write a test for this!

**Comment by danzilio** [comment]
So, let me preface this by saying I'm just getting started with Go...

What you think about the test I added here? Checking to make sure that `p.config.Facter` wasn't `nil` seemed good enough, but I'm still not entirely satisfied. I thought about mocking `PackerBuildName` and `PackerBuilderType` and testing to make sure that `Facter["packer_build_name"]` and `Facter["packer_builder_type"]` had the expected values, but that didn't seem particularly maintainable. What's the idiomatic way to test something like this?

**Comment by mitchellh** [comment]
LGTM

**Pull request merged**
