### PR TITLE
vmware-iso-builder: Fix for non consequential if statement (failing ESXi iso builds).

### PR DESCRIPTION
**Pull request by andqui**
To be honest I'm not entirely sure what the code is suppose to do here since it will have packer look for a local output directory when building remote using an ESXi host which causes a failure.

Added a test for non empty `b.config.Format` as it was added in the same commit that added the field and support for an export step. See commit 699c673 by higebu for clarification.

### CODE REVIEW

**Comment by cbednarski** [comment]
Thanks for the PR. I can't easily tell what the implications of this change are. Can you provide a unit test or an example configuration that demonstrates what is changed here?

**Comment by andqui** [comment]
The following configuration would report an error that it couldn't find a directory named `vmware-output-iso' on the machine running packer. But since the build is in fact running on the ESXi host the existence the directory would never be the case since everything is done on the remotely.
```
{
  "builders": [
    {
      "communicator": "winrm",
      "disk_size": "{{user `disk_size`}}",
      "floppy_files": [
        "floppy/00-run-all-scripts.cmd",
        "floppy/01-install-wget.cmd",
        "floppy/_download.cmd",
        "floppy/_packer_config.cmd",
        "floppy/fixnetwork.ps1",
        "floppy/install-winrm.cmd",
        "floppy/passwordchange.bat",
        "floppy/powerconfig.bat",
        "floppy/win2012r2-datacenter-esxi/Autounattend.xml",
        "floppy/zz-start-sshd.cmd"
      ],
      "guest_os_type": "windows8srv-64",
      "headless": "{{ user `headless` }}",
      "iso_checksum": "{{ user `iso_checksum` }}",
      "iso_checksum_type": "sha1",
      "iso_url": "{{ user `iso_url` }}",
      "shutdown_command": "{{ user `shutdown_command`}}",
      "tools_upload_flavor": "windows",
      "type": "vmware-iso",
      "vm_name": "win2012r2-datacenter",
      "vmx_data": {
        "cpuid.coresPerSocket": "1",
        "memsize": "4096",
        "numvcpus": "2",
        "scsi0.virtualDev": "lsisas1068",
        "ethernet0.networkName": "VLAN 121 Staging"
      },
      "winrm_password": "vagrant",
      "winrm_timeout": "5h",
      "winrm_username": "vagrant",
      "skip_compaction": true,
      "skip_vnc_connection": true,
      "remote_type": "esx5",
      "remote_host": "{{ user `remote_host`}}",
      "remote_username": "{{ user `remote_username`}}",
      "remote_password": "{{ user `remote_password`}}",
      "remote_datastore": "{{ user `remote_datastore`}}",
      "remote_cache_datastore": "{{ user `remote_datastore`}}"
    }
  ],
  "post-processors": [
  ],
  "provisioners": [
    {
      "environment_vars": [
        "CM={{user `cm`}}",
        "CM_VERSION={{user `cm_version`}}",
        "UPDATE={{user `update`}}"
      ],
      "scripts": [
        "script/vmtool.bat"
      ],
      "type": "windows-shell"
    },
    {
      "type": "windows-restart"
    },
    {
      "scripts": [
        "script/clean.bat"
      ],
      "type": "windows-shell"
    }
  ],
  "variables": {
    "cm": "",
    "cm_version": "",
    "disk_size": "45960",
    "headless": "false",
    "remote_host": "{{env `REMOTE_HOST`}}",
    "remote_username": "{{env `REMOTE_USERNAME`}}",
    "remote_password": "{{env `REMOTE_PASSWORD`}}",
    "remote_datastore": "{{env `REMOTE_DATASTORE`}}",
    "iso_checksum": "af9ef225a510d6d51c5520396452d4f1c1e06935",
    "iso_url": "iso/en_windows_server_2012_r2_with_update_x64_dvd_4065220.iso",
    "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
    "update": "true",
    "version": "0.1.0"
  }
}
```

**Comment by dave2** [comment]
If `b.config.Format` is defined, then that's passed as the extension on a local filename for ovftool to export the machine from ESXi. It tells ovftool what format it should be written in, but most importantly it does result in it being on the local filesystem even though it was a remote build.

Local export is actually used by #2962 (amazon-import post processor) as the input artifact to the upload to S3, since it needs a local directory to copy the exported machine from.

**Comment by andqui** [comment]
So we can agree on that it should not affect a remote build on an ESXi host as it does in the existing code, right?

**Comment by dave2** [comment]
Based on the test for step_export here:

https://github.com/mitchellh/packer/blob/master/builder/vmware/iso/step_export.go#L38

I believe the test you've proposed is correct. Even if remote type is defined, format needs to be non-empty for export to run, and so there should not be any attempt to check for a local export dir if format is empty.

**Comment by lazarus1331** [comment]
I can confirm this is still happening with version v0.10.0

Build 'vmware-iso' errored: lstat builds/packer-debian-8.3.0-amd64: no such file or directory

**Comment by ramsay-za-wonga** [comment]
I can confirm this is still happening with version v0.10.0

is there any workaround?

**Comment by kkinnear** [comment]
For what it is worth, we worked around this in v0.10.0 in the following way:

We have defined both "name" and "output_directory" in the .json file to be the same string value.  While we have no "format" defined, if we create a directory inside of the current working directory (current when we run packer) with the name we use for "name" and "output_directory", the failures go away.  I would guess that "output_directory" is the one being looked for, but we haven't tested that.  

We defined output_directory back when we started using packer a few years ago, kind of expecting that the vmware-iso builder would bring the VM back, though at the time, it did not. Or at least we couldn't figure out how to get it to do so. It is nice to see that now it will, and run ovftool for us too, but we haven't yet begun to use that capability.  We were just trying to upgrade to 0.10.0 and get the existing VM build we have working correctly when we ran into this problem.

**Comment by ricardclau** [comment]
Anything left to be done to accept this PR? 
At the moment we are compiling the latest packer with this patch in order to build VMWare templates in our ESXi so we would appreciate if this made 0.11 :)

**Comment by ricardclau** [comment]
Ping @cbednarski sorry to insist, really willing to help here. What would you need to move this PR forward?

**Comment by cbednarski** [comment]
@ricardclau Thanks for the ping! I just caught up on the discussion in the thread and this LGTM. Sorry to keep you waiting.

**Comment by ricardclau** [comment]
Thanks for merging @cbednarski ! No worries man, the amount of contributions and Pull Requests must be overwhelming, keep up the good work with all these tools

**Comment by rcorrieri** [comment]
Hello Team.
I am hitting an issue over and over, despite several changes I've addressed to my code.
Here is my JSON template (which I am creating from inside a Python script).

#! /usr/bin/env python

import json

vmware_tmpl = {
        "variables" : {
            "rem_user"    : "root",
            "rem_password": "1234!1234!",

            },
        "builders": [
            {
            "type"             : "vmware-iso",
            "iso_url"          : "/home/packerbuilder/.local/lib/python2.7/site-packages/packer_vm_builder/debian/wheezy/iso/debian-7.11.0-amd64-netinst.iso",
            "iso_checksum"     : "62876fb786f203bc732ec1bd2ca4c8faea19d0a97c5936d69f3406ef92ff49bd",
            "iso_checksum_type": "sha256",
            "remote_type"      : "esx5",
            "remote_host"      : "vmw-m02.oak.enova.com",
            "remote_datastore" : "VMW_PACKER_D00",
            "remote_username"  : "root",
            "remote_password"  : "1234!1234!",
            "vm_name"          : "packer_wheezy_2_2_8_tmpl",
            "output_directory" : "packer_wheezy_2_2_8_tmpl",
            "vmdk_name"        : "packer-wheezy_2_2_8_tmpl",
            "boot_wait"        : "5s",
            "ssh_username"     : "rcorrieri",
            "ssh_password"     : "rcorrieri",
            "disk_type_id"     : "eagerzeroedthick",
            "disk_size"        : 8192,
            "guest_os_type"    : "debian7-64",
            "http_directory"   : "/home/packerbuilder/.local/lib/python2.7/site-packages/packer_vm_builder/debian/wheezy/preseed",
            "shutdown_command" : "echo {{ user `rem_password`}} | sudo -S /sbin/shutdown -h now",
            "vmx_data": {
              "virtualHW.version" : "10",
              "ethernet0.virtualDev" : "vmxnet3",
              "ethernet0.networkName" : "VLAN 1904 - packer templates",
              "scsi0.virtualDev" : "pvscsi",
              "scsi0.present" : True,
              "scsi0:0.deviceType" : "scsi-hardDisk",
              "vcpu.hotadd" : True,
              "mem.hotadd" : True,
              "memsize": "2048",
              "numvcpus": "2",
              },
            "boot_command": [
                "<tab> auto=true priority=critical url=http://10.19.4.31:{{ .HTTPPort }}/wheezy-preseed.cfg",
                " <enter>"
            ],
            }
          ],
        "provisioners": [
            {
                "type": "file",
                "source": "/home/packerbuilder/.local/lib/python2.7/site-packages/packer_vm_builder/debian/wheezy/scripts/setup_enova_repo.sh",
                "destination": "/home/rcorrieri/setup_enova_repo.sh"
            },
            {
                "type": "file",
                "source": "/home/packerbuilder/.local/lib/python2.7/site-packages/packer_vm_builder/debian/wheezy/scripts/chef_sha256sum",
                "destination": "/home/rcorrieri/chef_sha256sum"
            },
            {
                "type": "shell",
                "execute_command": "echo 'rcorrieri' | {{.Vars}} sudo -S -E bash '{{.Path}}'",
                "script": "/home/packerbuilder/.local/lib/python2.7/site-packages/packer_vm_builder/debian/wheezy/scripts/setup_wheezy.sh"
            },
            {
                "type": "shell",
                "execute_command": "echo 'rcorrieri' | {{.Vars}} sudo -S -E bash '{{.Path}}'",
                "script": "/home/packerbuilder/.local/lib/python2.7/site-packages/packer_vm_builder/debian/wheezy/scripts/cleanup.sh"
            },
            {
                "type": "shell",
                "inline": [ "sleep 5; echo 'rcorrieri'|sudo -E -S shutdown -h now" ]
            }
        ],
    }
dict_to_json = json.dumps(vmware_tmpl)
fp = open('/home/packerbuilder/.local/lib/python2.7/site-packages/packer_vm_builder/debian/wheezy/templates/wheezy_2_2_8.json', 'w')
fp.write(dict_to_json)
fp.close()


This configuration works well, the packer process validates the generated JSON code and also the build succeeds.
But 3 minutes after the build has finished, the vCenter puts the just-created VM into 'orphaned' state. I've verified, and the disk files have been created in the ESXi server too.
Any ideas...?

I was running packer 0.10.0, and some minutes ago I changed into 0.10.0
According to this article, I also created on purpose an empty folder in my local Linux (where I am running this build).
No luck, the results are as I say.
Thanks.
Ricardo Corrieri

**Comment by rcorrieri** [comment]
Hello Team.

I am generating my JSON code from the following Python script:

#! /usr/bin/env python

import json

vmware_tmpl = {
        "variables" : {
            "rem_user"    : "my_user",
            "rem_password": "my_passwd",
            "vm_password" : "my_vm_password",
            },
        "builders": [
            {
            "type"             : "vmware-iso",
            "iso_url"          : "./debian/wheezy/iso/debian-7.11.0-amd64-netinst.iso",
            "iso_checksum"     : "62876fb786f203bc732ec1bd2ca4c8faea19d0a97c5936d69f3406ef92ff49bd",
            "iso_checksum_type": "sha256",
            "remote_type"      : "esx5",
            "remote_host"      : "my_target_esxi_server",
            "remote_datastore" : "my_remote_datastore",
            "remote_username"  : "my_user",
            "remote_password"  : "my_passwd",
            "vm_name"          : "packer_wheezy_2_2_8_tmpl",
            "output_directory" : "packer_wheezy_2_2_8_tmpl",
            "vmdk_name"        : "packer-wheezy_2_2_8_tmpl",
            "boot_wait"        : "5s",
            "ssh_username"     : "vm_user",
            "ssh_password"     : "vm_password",
            "disk_type_id"     : "eagerzeroedthick",
            "disk_size"        : 8192,
            "guest_os_type"    : "debian7-64",
            "http_directory"   : "./debian/wheezy/preseed",
            "shutdown_command" : "echo {{ user `my_passwd`}} | sudo -S /sbin/shutdown -h now",
            "vmx_data": {
              "virtualHW.version" : "10",
              "ethernet0.virtualDev" : "vmxnetX",
              "ethernet0.networkName" : "VLAN for packer templates",
              "scsi0.virtualDev" : "pvscsi",
              "scsi0.present" : True,
              "scsi0:0.deviceType" : "scsi-hardDisk",
              "vcpu.hotadd" : True,
              "mem.hotadd" : True,
              "memsize": "2048",
              "numvcpus": "2",
              },
            "boot_command": [
                "<tab> auto=true priority=critical url=http://x.x.x.x:{{ .HTTPPort }}/wheezy-preseed.cfg",
                " <enter>"
            ],
            }
          ],
        "provisioners": [
            {
                "type": "file",
                "source": "./debian/wheezy/scripts/setup_repo.sh",
                "destination": "/home/vm_user/setup_repo.sh"
            },
            {
                "type": "file",
                "source": "./debian/wheezy/scripts/chef_sha256sum",
                "destination": "/home/vm_user/chef_sha256sum"
            },
            {
                "type": "shell",
                "execute_command": "echo {{ `my_vm_password` }} | {{.Vars}} sudo -S -E bash '{{.Path}}'",
                "script": "./debian/wheezy/scripts/setup_wheezy.sh"
            },
            {
                "type": "shell",
                "execute_command": "echo {{ `vm_password` }} | {{.Vars}} sudo -S -E bash '{{.Path}}'",
                "script": "./debian/wheezy/scripts/cleanup.sh"
            },
            {
                "type": "shell",
                "inline": [ "sleep 5; echo {{ `my_vm_password` }} |sudo -E -S shutdown -h now" ]
            }
        ],
    }
dict_to_json = json.dumps(vmware_tmpl)
fp = open('./debian/wheezy/templates/wheezy_2_2_8.json', 'w')
fp.write(dict_to_json)
fp.close()

This code works well.
I am running packer build --vmware-iso from a wheezy x64 box.
packer validates the JSON template being generated, and the build itself succeeds.

The problem is that, after 3 minutes (or so) the build has finished, my vCenter (release 6.0) is setting my just-created VM into an 'orphaned' state.
So the only possible action I can take with that VM is... to delete it.

I was running packer 0.10.1 (with identical results),  and switched into packer 0.10.0, just to see if anything would change.

According to the notes posted here, I've also created a local folder where I am launching packer, with the same name than the VM. Which is also the same name for the 'output_directory'.
No luck.

Thanks for your help.

Ricardo Corrieri

**Comment by rickard-von-essen** [comment]
@rcorrieri your comment seems a bit random. Please don't comment on a merged PR if you don't have anything important to add. To ask for help use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that. See https://www.packer.io/community/ . A general suggestion if you have troubles with ESXi and packer is to build from master and see if it's fixed there since I just merged some fixes. See https://github.com/mitchellh/packer/blob/master/CONTRIBUTING.md#setting-up-go-to-work-on-packer .

**Comment by rcorrieri** [comment]
Hello Rickard, and thanks for your follow up.

You are right. It seems random because I didn't clarify that I had arrived
to these results following that thread of conversation on that PR.

I'll follow your directions for my troubleshooting.

Thanks.

Ricardo Corrieri

**Pull request merged**
