### PR TITLE
Better Windows support in puppet-server

### LINKED ISSUE #4384: puppet-server provisioner now more broken in Windows
Looks like 7feb8b993c5447bfeff5fce78781d736e5e3be7b activated a sleeper bug in the puppet-server provisioner. Previously, I guess `facterVars` was empty so the bug went unnoticed on Windows, but now that `facterVars` is populated with default values, the resulting `ExecuteCommand` is no longer compatible in Windows.

Windows doesn't support `ENVVAR=VAR command` style setting of environment variables per command, so the provisioner breaks thusly:

> ==> amazon-ebs: Provisioning with Puppet...
>     amazon-ebs: Creating Puppet staging directory...
>     amazon-ebs: Running Puppet: FACTER_packer_build_name='amazon-ebs' FACTER_packer_builder_type='amazon-ebs' puppet agent --onetime --no-daemonize --test --pluginsync --no-report --detailed-exitcodes
>     amazon-ebs: 'FACTER_packer_build_name' is not recognized as an internal or external command,
>     amazon-ebs: operable program or batch file.

Unfortunately I can't see an easy fix without either a lot of refactoring or terrible hacks which are worse than what I came up with for #3850.

Best fix for people like me who need to roll out Windows AMIs in this way is to rollback 7feb8b993c5447bfeff5fce78781d736e5e3be7b.

Tagging @seanmalloy for FYI.

Perhaps a short-term solution that doesn't involve rolling back this change is rolling forward with a configurable option in the puppet-server provisioner to omit FacterVars.

### PR DESCRIPTION
**Pull request by c22**
Reworking the puppet-server provisioner based on chef-client.

Paging @seanmalloy for review.

I've tested this against my Windows template, it works quite well and I was able to remove a lot of yucky workarounds from my packer template and do away with my mkdir patch.

@seanmalloy maybe you have time to give similar treatment to puppet-masterless?

Closes #4384
Closes mkdir issues described in #3850

### CODE REVIEW

**Comment by mwhooker** [comment]
this is basically the same as the `puppet-masterless` pr here https://github.com/mitchellh/packer/pull/3490

I closed it because there was some debate around deciding on the guest os type.

I'm not going to close this because it's obvious it's a problem for people and want to find a workable solution, however if I merge this then I want to reopen and merge the other one.

Given that the chef provisioner also uses the guest_os_type, and people don't seem to have issues with that, I'm tempted to merge as is. Will consider by next release

puppet-masterless issue: https://github.com/mitchellh/packer/issues/2566

**Comment by c22** [comment]
I'm biased towards a merge (for both PRs) because maintaining my own set of patches just to build Windows AMIs is cumbersome. Having said that, I'm in no way opposed someone taking a crack at a more unified approach.

Would a good middle ground be merging both these PRs and capturing your thoughts on unification in a separate issue? I'm happy to be tagged in whatever other issue is spawned and contribute effort to future clean up.

@stkerr thoughts?

**Comment by mwhooker** [comment]
@c22 any chance you want to add the changes in #3490 to your patch? That one seems to need a little bit of work: gofmt, documentation, I think `config_template` was copied from chef on accident, etc.

If you do that, and get can get some verification from someone that they work, I'll merge.

**Comment by c22** [comment]
@mwhooker, I just pushed the puppet-masterless changes, tried to retain as much of the work @stkerr put in 👍 

Can't verify puppet-masterless as I don't use it.

**Comment by seanmalloy** [comment]
I can test the change for puppet-server and puppet-masterless on Linux.
Hopefully in the next 24 hours.

--
Sean Malloy

**Comment by seanmalloy** [comment]
I did not have a chance to test this out today. I have the packer binary compiled and should be able to test it out tomorrow.

**Comment by mwhooker** [comment]
this is awesome! lgtm. I just want to get a quick test before merging

**Comment by mwhooker** [comment]
moved to #4426

**Pull request closed without merging**
