### PR TITLE
Get admin password of booted instance when using WinRM

### LINKED ISSUE #2663: Make admin password of booted instance available as template variable
I'm trying to build Windows images on OpenStack with packer, but I'm having some issues getting started. Our OpenStack provider has cloud-init Windows images which we'd like to use as the base image. In those, there is an admin account with credentials set during first boot, and this password is returned when booting the machine. 

In order to use WinRM, we need to set the `winrm_password` option to this admin password. I tried figuring out how to export it as a configuration template variable so I could just put `{{ .AdminPass }}`, but I'm not very fluent in Go, unfortunately. 

From the [gophercloud docs](http://godoc.org/github.com/rackspace/gophercloud/openstack/compute/v2/servers#Server) it seems this property is already exposed, so I'm guessing it just needs to be exposed somehow to the templating system?

### PR DESCRIPTION
**Pull request by rickard-von-essen**
Fixes #2663 

~~Depends on https://github.com/rackspace/gophercloud/pull/534~~ Merged to master

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Supersedes #3137

**Comment by rickard-von-essen** [comment]
@carlpett It would be awesome if you could try this fix, which also require the gophercloud PR mentioned above.

**Comment by carlpett** [comment]
Fantastic! I'll give it a try and report back. Great work!

**Comment by carlpett** [comment]
Some good and some bad: Retrieving the password does indeed work, but with a caveat: the password is not fetched until I manually dismiss a "You must change your password" dialog from the graphical console. This may just be caused by how my openstack provider prepare their cloudinit-images, though. 
I'm also having some winrm issues, but those are probably not related to the fetching of the password. Will try to sort them out to validate a full scenario, but at least we're getting somewhere :)

**Comment by carlpett** [comment]
I was able to fix the winrm issues, and as soon as that was in place the rest of the provisioning works. So, the only remaining stumbling block is the clicking in the console.
Are you seeing this as well?

**Comment by rickard-von-essen** [comment]
No, and I using the ones provide by cloudbase.it. Try one of those, you can
download the from their page.

**Comment by carlpett** [comment]
Sorry for the slow response, we had a series of emergencies at work which had to get priority. Did a quick test now, and it all works nicely.
Fantastic, thank you very much!

**Pull request merged**
