### PR TITLE
Update Packer Debug Docs for Cloud-Init Issue

### PR DESCRIPTION
**Pull request by grubernaut**
Update documentation to make official note of the cloud-init issue with
ubuntu AMIs.

Also ran `make format`

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
NOK diff, you have to update your commit to only include you proposed changes.

**Comment by grubernaut** [comment]
Updated, and removed `make format`

**Comment by rickard-von-essen** [comment]
:+1:

**Comment by grubernaut** [comment]
The amount of changes that were made from running `make format` probably suggests we should add that in, in a separate PR though :)

**Pull request merged**
