### PR TITLE
Allow specifying environment variables for ansible provisioner

### PR DESCRIPTION
**Pull request by mtb-xt**
This adds a parameter for the Ansible provisioner to set the environment variables for ansible-playbook execution. It's useful if you need to override anything from Ansible config file.

### CODE REVIEW

**Comment by cbednarski** [comment]
Thanks for the PR! The code looks good. Can you expand the docs to include an example? Unless you know that this maps to `cmd.Env` it may not be clear how to specify the key-value pairs.

**Comment by mtb-xt** [comment]
I've updated the docs with an example and more detailed description of the parameter.
Not sure I did the rebase of the pull request right, though...

**Comment by rickard-von-essen** [comment]
I think your rebase is busted.

You should not do PR's on an upstream (```master```) branch. In stead create a branch for the fix, say ```ansible-env```, work on that and push it to github (```git push mtb-xt ansible-env```, assuming your repos remote name is ```mtb-xt```). 

If there are some merge conflicts for us to merge the PR you have to do:
```
$ git checkout master
$ git pull origin master
$ git checkout ansible-env
$ git rebase master
$ git push mtb-xt ansible-env
```
The rebase will fail if there are any conflicts and you have to resolve them and then add the files (```git add...```) and then do ```git rebase --continue```.

The last command will also fail since you changed the history for your branch add ```--force``` to updated it.

The above example also asumes that you have this repo (```https://github.com/mitchellh/packer.git```) as remote ```origin```.

**Comment by cbednarski** [comment]
I'm working towards a 0.9 RC and trying to keep the scope from creeping, so I'm going to defer this one until an upcoming release.

**Comment by mtb-xt** [comment]
@rickard-von-essen Thanks for the tutorial! The proper thing to do would be for me to close this PR and open a new one, or this one can be fixed? Can I override my commits with --force?

**Pull request closed without merging**
