### PR TITLE
Prepending -i to sudo so PATH is inherited from profile.d scripts

### PR DESCRIPTION
**Pull request by bhourigan**
This patch addresses problems mentioned in https://github.com/mitchellh/packer/issues/1929

### CODE REVIEW

**Comment by sethvargo** [comment]
:+1: my only concern is which versions of sudo (on which OSes) support `-i`. Do you have any information on that?

**Comment by bhourigan** [comment]
Hi Seth! Great question. Anecdotally I've never encountered a Linux variant that did *not* accept the -i flag, but I did some digging just to be sure.

I checked [FreeBSD](http://www.freebsd.org/cgi/man.cgi?query=sudo&apropos=0&sektion=0&manpath=FreeBSD+8.1-RELEASE+and+Ports&format=html), [OSX](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/sudo.8.html), [Ubuntu](http://manpages.ubuntu.com/manpages/karmic/en/man8/sudo.8.html), [Debian](http://manpages.debian.org/cgi-bin/man.cgi?sektion=8&query=sudo&apropos=0&manpath=sid&locale=en), [CentOS](http://grisha.biz/cgi-bin/man?query=sudo&apropos=0&sektion=0&manpath=CentOS+release+5.3+%28Final%29&format=html), and [sudo 1.8.11's distribution independant man page](http://www.sudo.ws/sudo/man/1.8.11/sudo.man.html) and it looks like it is supported.

I checked Amazon Linux and RedHat, both of which also support the -i flag. I couldn't find a HTML version of those man pages, but that should be pretty easy to independently verify.

**Comment by ramsey** [comment]
Should it be `-i` in all the places. It looks like you left off the dash in a few of the places.

This would be great to have. I'm running into this problem, as well.

**Comment by jszwedko** [comment]
Ran into this issue recently as well and worked around it by altering the `secure_path`, but something like this would be friendlier. As @ramsey notes, you missed the `-` in a couple of places.

**Comment by bhourigan** [comment]
You're absolutely right. I had originally fixed these in master but ported them by hand to branches for a PR, and omitted the hyphen on all but the first sudo entry. Thanks @ramsey for fixing this upstream. My PR still has updates to the documentation.

**Comment by mitchellh** [comment]
LGTM

**Pull request merged**
