### PR TITLE
F expose openstack image

### PR DESCRIPTION
**Pull request by jcejohnson**
Adds `image_info_file` and `image_info_content` configuration options to the Openstack builder so that post-processors have access to the image id (e.g. -- via the artifice post-processor).

Relates to #2678

### CODE REVIEW

**Comment by jcejohnson** [comment]
Is there anything I need to do on this?

**Comment by rickard-von-essen** [comment]
I'm not sure this is a good way forward.

I think fixing the `shell-local` post-processor to run once per artifact expose `Artifact.Id` to it is a better way forward.

**Comment by jcejohnson** [comment]
I took this route so that any post-processor would have access to the image id.
Would Artifact.Id be the actual Openstack image ID or a packer ID?

**Comment by rickard-von-essen** [comment]
OpenStack image ID

**Comment by jcejohnson** [comment]
Perfect! Point me in the right direction and I'll see what I can do.

**Comment by rickard-von-essen** [comment]
> Point me in the right direction and I'll see what I can do.

See #3671

**Comment by jcejohnson** [comment]
I've updated the PR based on your suggestion.
This change doesn't attempt to address the full scope of #3671. Instead, it simply uses artifact.Id() as the template .Artifact value when artifact.Files() returns nil. This maintains backward compatibility when a builder produces files while behaving reasonably when it doesn't and removes the need for fake artifacts.
I have also backed out my original changes to builder/openstack/*

**Comment by gkuchta** [comment]
Any movement on this? It'd be very, very useful, as packer currently uses the nova API for creating images, which doesn't allow you to control whether an image is public/private. This is problematic when used with something like Spinnaker.

**Comment by rickard-von-essen** [comment]
@gkuchta It would be better if someone PR'ed #2678

**Comment by gkuchta** [comment]
@rickard-von-essen agreed. our team is looking at either PR'ing the base builder to use the image api or writing an openstack post-processor longer term.

**Comment by rickard-von-essen** [comment]
@gkuchta Sounds great, the problem have being getting in Glance support into [gophercloud](https://github.com/rackspace/gophercloud), see https://github.com/rackspace/gophercloud/issues/213#issuecomment-124035737 and we probably need to migrate to [gophercloud org](https://github.com/gophercloud/gophercloud) before getting Glance support.

**Comment by mwhooker** [comment]
We're planning to rewrite the shell-local post-processor, so this change is unnecessary.

Will also be happy to take a look at a PR of #2678 since it looks like the upstream changes have been merged.

**Comment by mwhooker** [comment]
see also #4113 for possible glance support

**Pull request closed without merging**
