### PR TITLE
Windows provisioners: powershell, windows-shell, windows-restart

### LINKED ISSUE #1309: Powershell Provisioner
Hi,

I'm trying to run a powershell script as provisioner in my windows build, but it seems the provisioner only supports batch files. Are PS scripts supported ?

Carl

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #1309 

This adds three new provisioners to Packer exclusively for Windows:

* `powershell` - Execute PowerShell scripts, optionally with elevated privs.
* `windows-shell` - Execute shell scripts using `cmd`
* `windows-restart` - Restart Windows and wait for it to reboot, especially important since reboots are a critical part of provisioning Windows.

Thanks to the packer-windows-plugins repo for doing all the hard work, I just ported them over: https://github.com/packer-community/packer-windows-plugins

### CODE REVIEW

**Comment by pecigonzalo** [comment]
The windows-restart provisioner fails with error code 1. Same happens over at https://github.com/packer-community/packer-windows-plugins/issues/54.
Seems the issue started after some updates to masterzen/winrm

**Comment by mitchellh** [comment]
@pecigonzalo I commented over on that thread. It would be nice to fix that.

**Comment by pecigonzalo** [comment]
I did some more investigation:

Seems that when the WinRM starts after a reboot, the winrm client tries to "talk" to it again, but gets error: ```unknown error Post http://localhost:13336/wsman: EOF``` this is returned as an error and kills the entire build process. Probably because its not re creating the channel and starting the communication again.

If i revert https://github.com/masterzen/winrm/pull/25 (just change the cmd.err to nil) and compile, it just returns no error and that is why it was previously working. 

I managed to get a rebooter working using a different reboot command not stopping winrm manually, maybe this could be used as an interim solution, if you agree ill open a pull request to this branch.
```
Restart-Computer -force
```
or
```
shutdown /r /c \"packer restart\" /t 2 /f
```
This gives time for the command to finish executing and return but not to reconnect preventing the next provisioner to start executing mid reboot. ```/f```/```-force``` forces all services to terminate immediately.

Notes:
* Any other commands in the script are dropped after the WinRM service is stopped and the script execution halted, meaning any solutions relaying on subsequent commands after stopping winrm like this will not work.
EG: 
If i execute this WinRM will not start again
```
Stop-Service WinRM

Start-Sleep 5

Start-Service WinRM
```


* Powershell implements a remote rebooter as ```Restart-Computer``` using WSMan or DCOM as checked by reflecting: ```C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Microsoft.PowerShell.Commands.Management\v4.0_3.0.0.0__31bf3856ad364e35\Microsoft.Powershell.Commands.Management.dll```

Maybe we could extrapolate a better solution from that reflection, although i was not yet able to do it and i think this will need to be implement at https://github.com/masterzen/winrm .

**Comment by mitchellh** [comment]
@pecigonzalo That sounds like a good fix. If you can verify that, I'd be happy to accept that PR.

**Comment by mitchellh** [comment]
Incoming.

**Comment by mefellows** [comment]
Nice work @pecigonzalo. I think I have a more stable workaround, as this won't solve issues like packer-community/packer-windows-plugins/issues/51 which a more generic in nature.

**Comment by pecigonzalo** [comment]
@mefellows Can you share the workaround? Im working on a permanent fix on masterzen/winrm as ultimately the issue is on how that handles the early termination of the connection or reconnection, ill upload my code today and put a link here so we can all work on it as there might be better ways of coding what im trying to do hehehe.

**Comment by mefellows** [comment]
@pecigonzalo commenting out these [lines](https://github.com/mitchellh/packer/blob/master/provisioner/windows-restart/provisioner.go#L92-L94) from the restart provisioner (and https://github.com/mitchellh/packer/blob/master/builder/vmware/common/step_shutdown.go#L64-L69 from the VMWare builder) should be sufficient for a temporary fix. VMWare seems to be the only builder that checks the exit code of the shutdown command.

I think I have a longer term solution for the restart provisioner, but need to find 10GB of free space...

**Comment by mefellows** [comment]
Actually now that I've taken a deeper look, at least on the Packer side of things, your workaround might be sufficient, if not totally solid (I can't think of a scenario where it would fail, but it _feels_ like we don't have full control over the situation). My preferred approach would be to add a wait routine that would run before `waitForCommunicator` which checks for the exact opposite situation - the _lack_ of a connection to the box and once that check is satisfied it can then it can begin its wait for the reboot. However at this point in the pipeline things are a bit tough - I'm not sure if we can get a handle to the WinRM connection info but if we could, that would make this a cinch (i.e. `net.Dial...`).

**Comment by pecigonzalo** [comment]
On my test cases the only situation where i had to add waits is after updates(not all of them but it might be a good idea and SP1) as machine starts rebooting but it doesnt stop the process. I think for this cases you can either add a wait next, or change the reboot command to ```Restart-Computer -force; Stop-Service WinRM```  and specify 1 as a valid exit code.

I like the idea of adding a wait for disconnect loop as a hacky improvement to the current workaround.
Another idea would be to add a schedule task that runs Stop-Service WinRM when it detects a reboot, i believe this will run after your command finished and it will give it time to disconnect properly but it will not give us any output weather it ran correctly or not.
I prefer your addition tbh, the wait till its down routine. 

Im working on the WinRM side of things now as i think its not handling it properly, maybe if we had a more verbose error code or something we could handle it better on the packer side as well.
We will also need to change the winrm communicator on this project eventually, but one at a time hehe.

**Pull request merged**
