### PR TITLE
remoteValidationKeyPath was being set AFTER client.rb file was written

### PR DESCRIPTION
**Pull request by troylarv1**
Because remoteValidationKeyPath was not being set before the client.rb file was written, it would never write ValidationKeyPath to the file, causing chef to always look for the file at c:\chef\validation.pem instead of {StagingDir}\validation.pem.

### CODE REVIEW

**Comment by b-dean** [comment]
This seems to fix #3263. I don't really understand what that AppVeyor thing is complaining about but is there a chance anyone could fix this so it can be merged? I would really like to use the chef-client provisioner on 0.9.0

**Comment by rickard-von-essen** [comment]
You can ignore the AppVeyor failure, it's been broken for a long time now. HashiCorp is going to fix it soon.

**Comment by sarkis** [comment]
Any updates on merging this in?

**Comment by mwhooker** [comment]
Looks like this is fixed in master

https://github.com/mitchellh/packer/blob/master/provisioner/chef-client/provisioner.go#L254-L271

closing, but please re-open if I'm missing something

**Pull request closed without merging**
