### PR TITLE
amazon/common/ssh: fix saving of instance to state

### LINKED ISSUE #3496: Packer crash: unexpected EOF, interface conversion panic
This happened one time so far. Prior and subsequent builds have been fine but any straight-up panic is cause for concern. Haven't been able to find a matching issue, just other "unexpected EOF" tickets from other situations.

Relevant snippet from log:

```
2016/05/03 21:54:11 Waiting on builds to complete...
2016/05/03 21:54:11 Starting build run: amazon-ebs
2016/05/03 21:54:11 Running builder: amazon-ebs
2016/05/03 21:54:11 ui: ==> amazon-ebs: Prevalidating AMI Name...
2016/05/03 21:54:26 ui: ==> amazon-ebs: Inspecting the source AMI...
2016/05/03 21:54:26 ui: ==> amazon-ebs: Creating temporary keypair: packer 67291e03-e838-bc89-57c4-9e02ce671d61
2016/05/03 21:54:26 packer: 2016/05/03 21:54:26 Using specified security groups: [sg-redacted]
2016/05/03 21:54:26 ui: ==> amazon-ebs: Launching a source AWS instance...
2016/05/03 21:54:26 ui:     amazon-ebs: Instance ID: i-d776985d
2016/05/03 21:54:26 ui: ==> amazon-ebs: Waiting for instance (i-d776985d) to become ready...
2016/05/03 21:54:26 packer: 2016/05/03 21:54:26 Waiting for state to become: running
2016/05/03 21:54:26 packer: 2016/05/03 21:54:26 Allowing 300s to complete (change with AWS_TIMEOUT_SECONDS)
2016/05/03 21:55:04 packer: 2016/05/03 21:55:04 [INFO] Not using winrm communicator, skipping get password...
2016/05/03 21:55:04 packer: 2016/05/03 21:55:04 [INFO] Waiting for SSH, up to timeout: 5m0s
2016/05/03 21:55:04 ui: ==> amazon-ebs: Waiting for SSH to become available...
2016/05/03 21:55:06 packer: panic: interface conversion: interface {} is **ec2.Instance, not *ec2.Instance
2016/05/03 21:55:06 packer: 
2016/05/03 21:55:06 packer: goroutine 199 [running]:
2016/05/03 21:55:06 packer: panic(0x11b4100, 0xc8205f86c0)
2016/05/03 21:55:06 packer: 	/usr/local/go/src/runtime/panic.go:464 +0x3e6
2016/05/03 21:55:06 packer: github.com/mitchellh/packer/builder/amazon/common.SSHHost.func1(0x7fb3716402a8, 0xc820452b70, 0x0, 0x0, 0x0, 0x0)
2016/05/03 21:55:06 packer: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/builder/amazon/common/ssh.go:19 +0x70d
2016/05/03 21:55:06 packer: github.com/mitchellh/packer/helper/communicator.(*StepConnectSSH).waitForSSH(0xc82033df40, 0x7fb3716402a8, 0xc820452b70, 0xc820011620, 0x0, 0x0, 0x0, 0x0)
2016/05/03 21:55:06 packer: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/helper/communicator/step_connect_ssh.go:119 +0x6e9
2016/05/03 21:55:06 packer: github.com/mitchellh/packer/helper/communicator.(*StepConnectSSH).Run.func1(0x7fb37163fd48, 0xc8204acfa0, 0xc8202a3bb0, 0xc8202a3bc0, 0xc82033df40, 0x7fb3716402a8, 0xc820452b70, 0xc820011620, 0xc8201d7dc0)
2016/05/03 21:55:06 packer: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/helper/communicator/step_connect_ssh.go:39 +0x78
2016/05/03 21:55:06 packer: created by github.com/mitchellh/packer/helper/communicator.(*StepConnectSSH).Run
2016/05/03 21:55:06 packer: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/helper/communicator/step_connect_ssh.go:41 +0x1c0
2016/05/03 21:55:06 ui error: Build 'amazon-ebs' errored: unexpected EOF
2016/05/03 21:55:06 /usr/bin/packer: plugin process exited
2016/05/03 21:55:06 Builds completed. Waiting on interrupt barrier...
2016/05/03 21:55:06 machine readable: error-count []string{"1"}
2016/05/03 21:55:06 ui error: 
==> Some builds didn't complete successfully and had errors:
2016/05/03 21:55:06 machine readable: amazon-ebs,error []string{"unexpected EOF"}
2016/05/03 21:55:06 ui error: --> amazon-ebs: unexpected EOF
2016/05/03 21:55:06 ui: 
==> Builds finished but no artifacts were created.
2016/05/03 21:55:06 waiting for all plugin processes to complete...
2016/05/03 21:55:06 /usr/bin/packer-post-processor-ami-file: plugin process exited
2016/05/03 21:55:06 /usr/bin/packer: plugin process exited
```

Packer 0.9.0 on Ubuntu 14.04.3

### PR DESCRIPTION
**Pull request by dpiddy**
Fixes #3496

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Could you describe a simple test that provoke the bug?

**Comment by dpiddy** [comment]
If [this check](https://github.com/mitchellh/packer/blob/42144640658ded0e55be62984642750ffc4978db/builder/amazon/common/ssh.go#L30) fails due to the instance not having an IP or hostname available, we describe it again and stash in state. When the next loop iteration runs, the just-fetched instance is fetched from state.

Without this fix, the item stashed in state will be **ec2.Instance and the type assertion [here](https://github.com/mitchellh/packer/blob/42144640658ded0e55be62984642750ffc4978db/builder/amazon/common/ssh.go#L19) fails.

So a test case would need to set things up so that `host != ""` check fails, the instance is described again, stashed in state, and then pulled out in a subsequent loop iteration.

I can try to add that test case to this but it will take me a bit longer.

**Comment by dpiddy** [comment]
Updated with tests. They brought out that with current structure that there was effectively only one try. I didn't change the structure but changed the loop setup to try describing twice which I gathered was the intent.

**Comment by rickard-von-essen** [comment]
:+1:

**Pull request merged**
