### PR TITLE
allow to specify checksum via url

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@selfip.ru>

### CODE REVIEW

**Comment by vtolstov** [comment]
ping

**Comment by vtolstov** [comment]
@mitchellh @cbednarski @rickard-von-essen can you review? why packer team slowdown review pr ?

**Comment by cbednarski** [comment]
@vtolstov Sorry about the delay on review. I've been helping out with Nomad lately, but I'll be switching back over to Packer in a week or two so we can get many of these PRs merged soon and get 0.9 out. Thanks for your patience!

**Comment by vtolstov** [comment]
@cbednarski may be this can be merged? i'm use this is about 1,5 month and all works fine.

**Comment by cbednarski** [comment]
@vtolstov Thanks for the PR and sorry to keep you waiting for a review! Can you add some documentation?

**Comment by vtolstov** [comment]
Thanks, i'm add docs.

**Comment by cbednarski** [comment]
@vtolstov Thanks for adding documentation! How do you feel about adding a new field called `iso_checksum_url`? I think it will be easier to keep backwards compatibility if we do not overload `iso_checksum`. I can make this change if you like but I want to make sure this does not break your use-case. Thoughts?

**Comment by vtolstov** [comment]
Thanks! No problem, change as you like
29 янв. 2016 г. 2:29 пользователь "Chris Bednarski" <
notifications@github.com> написал:

**Comment by vtolstov** [comment]
ping...

**Comment by vtolstov** [comment]
@rickard-von-essen any change to get this merged?

**Comment by rickard-von-essen** [comment]
@vtolstov I'll merge it Monday if @cbednarski don't beat me.

**Comment by rickard-von-essen** [comment]
I'm adjusting this according to @cbednarski comments, improving error handling and adding some tests. brb soon.

**Comment by rickard-von-essen** [comment]
@vtolstov I have trouble parsing BSD style checksum file. Do you agree that they should look like:

```
SHA1 (filename) = b40881aa7493f8c216a4ac77063acb641a992ae2
```
[Real world example](http://ftp.freebsd.org/pub/FreeBSD/releases/ISO-IMAGES/10.2/CHECKSUM.MD5-FreeBSD-10.2-RELEASE-amd64)

And for reference GNU style should look like:
```
b40881aa7493f8c216a4ac77063acb641a992ae2 *binary_file
b40881aa7493f8c216a4ac77063acb641a992ae2  text_file
```

**Comment by vtolstov** [comment]
=) may be i miss something, i never read any rfc how checksum must looks =) I'm use this code for various distor mirrors like debian, fedora, ubuntu and so.

**Comment by rickard-von-essen** [comment]
Superseed by #3162

**Pull request closed without merging**
