### PR TITLE
Chef-client provisioner: Add encrypted data bag secret path (Fixes #1945)

### LINKED ISSUE #1945: Support encrypted data bag secret
Similar to how the validation key is currently handled you should be able to provide a local path to your encrypted data bag secret so that your chef client runs can use this.  Currently you have to use a file then shell provisioner before the chef client provisioner to upload the file and then move a file into place.  The workflow could be greatly simplified for new users.

### PR DESCRIPTION
**Pull request by eherot**

### CODE REVIEW

**Comment by cbednarski** [comment]
Thanks for the PR! I skimmed the code and things look great! Can you add some docs under the website folder? I think it would be good to explain how this works by listing the config options and giving an example of how they should be specified. When encryption is misconfigured it's pretty opaque to troubleshoot. I'm planning to include this in `0.9.0`, but I don't have a scheduled release date yet. Thanks!

**Comment by eherot** [comment]
Hi @cbednarski, absolutely! I should be able to get to this tomorrow.

**Comment by tas50** [comment]
Great fix here @eherot  Can't wait to get rid of my file provisioner and use this instead.

**Comment by eherot** [comment]
OK, Added docs to the website (sorry that took so long--it got back burnered). @cbednarski

**Comment by tas50** [comment]
Thanks @eherot

**Comment by cbednarski** [comment]
Thanks!

**Pull request merged**
