### PR TITLE
Update qemu builder doc net_device list, put things in packer fix order

### PR DESCRIPTION
**Pull request by tylert**

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
@vtolstov Could you quickly review this since you work allot with qemu?

**Comment by tylert** [comment]
For reference, I obtained this list from master HEAD (commit 3d9410f) builder/qemu/builder.go netDevice and diskInterface.  Thanks again for the prompt reply.

**Comment by vtolstov** [comment]
As i see all fine, so LGTM

**Comment by cbednarski** [comment]
:+1: Thanks guys!

**Pull request merged**
