### PR TITLE
post-processor/manifest: fixes interpolation of output

### LINKED ISSUE #4180: post-processor/manifest variables in filename
unfortunately the variable ```{{.Provider}}``` in this doesn't work:
```
"filename": "../builds/{{.Provider}}/{{ user `PACKER_BOX_NAME` }}_{{.Provider}}.manifest.json",
```
output is:
```
Unable to write ../builds/<no value>/debian-8.6.0-amd64_<no value>.manifest.json
```
And it would be nice to stick to the naming of other post-processors and name it "output" instead of "filename".

### PR DESCRIPTION
**Pull request by vtolstov**
Closes #4180

* rename `filename` to `output` for consistent with other post-processors
* interpolate output with variables

Signed-off-by: Vasiliy Tolstov <v.tolstov@selfip.ru>

### CODE REVIEW

**Comment by vtolstov** [comment]
@rickard-von-essen i don't understand why appveyor fails..

**Comment by rickard-von-essen** [comment]
Strictly this needs a fixer to migrate `filename` to `output`. @mwhooker you call.

**Comment by mwhooker** [comment]
was thinking the same re fixer. seems like a good change, though

**Comment by vtolstov** [comment]
2016-11-22 0:18 GMT+03:00 Matthew Hooker <notifications@github.com>:
>
> was thinking the same re fixer. seems like a good change, though


I don't know how to write fixers =(


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@selfip.ru

**Comment by mwhooker** [comment]
@vtolstov I'll take care of it

**Pull request closed without merging**
