### PR TITLE
Add winrm functionality to null provisioner

### PR DESCRIPTION
**Pull request by pecigonzalo**
Ref #2439 

Some more work needs to be done to improve the communicator helper and generalize even more all interactions with it, but i think falls out of the scope of this, so ill do it as a separate PR.
There is still a lot of code referencing SSH stuff.

### CODE REVIEW

**Comment by cbednarski** [comment]
Thanks for the PR! Is there a way to keep the communicator-specific error messages? I think it's useful to indicate which fields are missing without having to guess or reference the docs, especially if we know already which fields we're inspecting.

**Comment by pecigonzalo** [comment]
Thats actually a great idea, but it needs to be implemented on the communicator, the current error messages are implemented on the null builder, so i implemented them there.

BTW, build is failing at the updatedeps :confused:

**Comment by pecigonzalo** [comment]
Ok Build is passing now. 
About the moving the errors, i think that should be part of a different pull request, as it requires modifying all cases of ```Host()``` or ```Port()``` etc to accept ```string``` and ```err``` and handle the ```err```
Thoughts?

**Comment by pecigonzalo** [comment]
Merge?

**Comment by cbednarski** [comment]
Yep LGTM, thanks @pecigonzalo!

**Pull request merged**
