### PR TITLE
Add Debian 8.4 to gotchas for google compute builder

### PR DESCRIPTION
**Pull request by grobinson-blockchain**
**DELETE THIS TEMPLATE BEFORE SUBMITTING**

Describe the change you are making here!

Please include tests. Check out these examples:

- https://github.com/mitchellh/packer/blob/master/builder/virtualbox/common/ssh_config_test.go#L19-L37
- https://github.com/mitchellh/packer/blob/master/post-processor/compress/post-processor_test.go#L153-L182

If your PR resolves any open issue(s), please indicate them like this so they will be closed when your PR is merged:

Closes #xxx
Closes #xxx

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Could you provide a description and a ref to the change in debian.

**Comment by rickard-von-essen** [comment]
@cbednarski In general I think these hints should not be placed in the builders since they apply to all builders and are just related to the OS.

**Comment by grobinson-blockchain** [comment]
@rickard-von-essen I don't know whether the change applies to all Debian images per say, but I can confirm that all recent Debian images on GCE (version > 8.4) now have root login disabled by default in their `/etc/ssh/sshd` configuration file.

**Comment by cbednarski** [comment]
>  In general I think these hints should not be placed in the builders since they apply to all builders and are just related to the OS.

@rickard-von-essen I agree this is not the "best" place but I think it's fine to document these workarounds alongside the builder. While it's technically related to the OS, for anyone trying to use packer to build that OS this is a packer problem. If we can save them a small headache with a few lines in the docs mentioning a workaround I think that is a better experience with Packer overall.

@grobinson-blockchain Thanks for the contribution!

**Comment by rickard-von-essen** [comment]
> While it's technically related to the OS, for anyone trying to use packer to build that OS this is a packer problem. If we can save them a small headache with a few lines in the docs mentioning a workaround I think that is a better experience with Packer overall.

Yes, maybe we should think about a new section of the documentation which is only about how to build different OS. With examples, links to good example reposes and things like kickstart documentation.

**Comment by cbednarski** [comment]
@rickard-von-essen Yeah that's a good idea. I've thought about expanding the examples folder a bit. We could also link to some prominent community-maintained templates.

**Pull request merged**
