### PR TITLE
ansible-local provisioner: add a `playbook_file_dir` var

### LINKED ISSUE #853: Target Playbook path should be configurable
To allow playbooks transferred to the root of the staging directory as described on the ansible best practise page here:

http://docs.ansible.com/playbooks_best_practices.html

### PR DESCRIPTION
**Pull request by tamsky**
This only affects the destination copy directory (and exec path) of `playbook_file` on the remote.

Fixes #853

### CODE REVIEW

**Comment by tamsky** [comment]
Rebased to master

**Comment by tamsky** [comment]
All checks pass now.

**Comment by tamsky** [comment]
Please let me know if there are any actions I can take that would help get this merged.

**Comment by rickard-von-essen** [comment]
Could you write a simple example here? I don't get it to work..

**Comment by tamsky** [comment]
@rickard-von-essen I've placed examples of usage, output, and provisioner trees (both with and without this PR) in https://github.com/tamsky/packer-pull-3356/blob/master/README.md

https://github.com/tamsky/packer-pull-3356 contains the rest of the simple example.

Hopefully the use case and file trees will illustrate the need and what behavior this patch changes.

Please let me know if you still have questions.

**Comment by rickard-von-essen** [comment]
I think there is some error cases that we should try to protect against in prepare. 

If you run with:
```json
    {
      "type": "ansible-local",
      "playbook_file_dir": "playbooks",
      "playbook_file": "playbooks/local.yml",
      "playbook_dir": "playbooks"
    }
```

With file tree:
```
.
├── playbooks
│   └── local.yml
└── pr_3356.json
```

You get:
```
    null: Uploading Playbook directory to Ansible staging directory...
    null: Creating directory: /tmp/packer-provisioner-ansible-local
    null: Uploading main Playbook file...
    null: Uploading inventory file...
    null: Executing Ansible: cd /tmp/packer-provisioner-ansible-local && ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/packer-provisioner-ansible-local/playbooks/local.yml -c local -i /tmp/packer-provisioner-ansible-local/packer-provisioner-ansible-local618009202
    null: ERROR! the playbook: /tmp/packer-provisioner-ansible-local/playbooks/local.yml could not be found
Build 'null' errored: Error executing Ansible: Non-zero exit status: 1
```

And in the target VM you get:
```
[root@centos-7 packer-provisioner-ansible-local]# ls -l
total 52
-rw-r--r--. 1 vagrant vagrant 64 Aug 24 20:04 local.yml
-rw-r--r--. 1 vagrant vagrant  9 Aug 24 19:59 packer-provisioner-ansible-local419624947
-rw-r--r--. 1 vagrant vagrant 64 Aug 24 20:04 playbooks <-----
```

Can you have a look into this?

**Comment by tamsky** [comment]
Thanks for looking at this.  I'll take a look at the error case and work on it this week.

I'm not very experienced doing localhost testing...

Can you share the packer file you're using for testing?
Are you using a `null` builder, configured to ssh to a localhost VM?

**Comment by rickard-von-essen** [comment]
This is how I do:

Vagranfile:
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.2"
end
```

Packer template:
```json
{
  "builders": [
    {
      "type": "null",
      "ssh_host": "10.211.55.14",
      "ssh_username": "vagrant",
      "ssh_password": "vagrant"
    }
  ],
  "provisioners": [
    {
      "type": "ansible-local",
      "playbook_file_dir": "playbooks",
      "playbook_file": "playbooks/local.yml",
      "playbook_dir": "playbooks"
    }
  ]
}
```

Just do `vagrant up` and replace the `ssh_host` with the ip of you vagrant host and then run `PACKER_LOG=1 packer build template.json`.

That is the quickest way to test out provisioners.

**Comment by mwhooker** [comment]
untargeting this for 0.11 since this doesn't look like it's working quite yet

**Comment by tamsky** [comment]
> I think there is some error cases that we should try to protect against in prepare
@rickard-von-essen I understand the error condition you're pointing out and what we'd need to do to protect against such in Prepare().

I recently read @korotovsky 's proposal in his https://github.com/mitchellh/packer/issues/3782#issue-169692269 which might be a better/simpler approach.

After I began to write logic into `func (p *Provisioner) Prepare(raws ...interface{})`...
I'm left feeling his design ("avoid copying `playbook_file`") will probably end up being cleaner, and easier to maintain.

If y'all might take a moment to compare these two approaches, I'd be interested to hear if the Packer project folks have a preference.

**Comment by mwhooker** [comment]
It seems like the consensus is that another approach is preferable. If you'd like to get this in, please address the `needs-more-tests` label, and submit a new PR

c&ping my respnse from #3782 

Hi folks,

I'm fairly agnostic about what changes get made to the ansible provisioner. I would like for someone from the community to decide if this approach, or the one in #3356 is better, and then submit a PR to resolve the issue.

However, this is not something we're targeting for 1.0, so I'm going to close this. We rely on the community to support this provisioner, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

**Pull request closed without merging**
