### PR TITLE
add virtio-scsi to packer

### PR DESCRIPTION
**Pull request by vtolstov**
By default packer when user specify scsi disk interface, spawn qemu with scsi emulation.
But virtio-scsi have much more speed and widely supported.

### CODE REVIEW

**Comment by vtolstov** [comment]
please, merge it. firstly it provides more speed then scsi, also this is needed for discard functionality.

**Comment by tylert** [comment]
+1 for merge

**Comment by cbednarski** [comment]
@vtolstov Does this require configuration changes or does it become the new default? From your description it sounds like it should be the default, provided it is backwards-compatible.

Also could you look into adding a test? This is fairly deep in the implementation and I am not familiar enough to eyeball this. I will likely spend some more time with QEMU for the next block of packer work I do so I will have some time to look at it in more detail.

**Comment by beddari** [comment]
This is a high profile feature for the qemu bilder, enabling discard support would be very useful and make it easier to build raw format sparse images. I've briefly tested this as working (though not extensively). Not sure about backwards compat or how it would be testable ...

**Comment by vtolstov** [comment]
to add this, firstly packer team needs to merge #2422

**Comment by beddari** [comment]
Yup, having a version check in place is good as it might be needed in more cases in the future. Thanks for your work on this @vtolstov

**Comment by vtolstov** [comment]
close this pr, use #2422

**Pull request closed without merging**
