### PR TITLE
Salt provisioner updates

### LINKED ISSUE #2486: Unable to remove --retcode-passthrough from salt-call in salt-masterless provisioner
It would nice if there was a way to remove that option since there are cases like mine where some salt-states will fail, but I don't want the entire build to fail because of it.

It seems like the best way to implement this would be to have an option in that provisioner that allows you send custom arguments to the salt call that is performed, similar to the way that arguments can be passed to the salt-bootstrap script.

I might be able to put some work in on this, but if anyone else can implement it quickly it would be greatly appreciated.

### LINKED ISSUE #2652: Salt provisioner: remote_state_tree option problem
**Problem**

The change introduced in 769c82b added two new variables `RemoteStateTree` and `RemotePillarTree`, which break the Salt provisioner for me. These variables allow the user to specify where on the packer-built guest OS that the Salt state and pillar files will be uploaded.

These new variables correspond to the Salt config options `file_roots` and `pillar_roots`, which traditionally are set in the minion's config file at `/etc/salt/minion`.

The change in 769c82b provides a way for a user to configure the specific paths for their states and pillar files on the guest OS, without having to go to the effort of writing a minion config (which would be passed in the Packer variable `minion_config`).

The issue is that `remote_state_tree` and `remote_pillar_roots` are passed to `salt` as command line arguments, which override any configuration supplied in the minion config - and this breaks my build.

**Proposed Solution**

Modify the provisioner such that if `minion_config` is supplied, the parameters `--file-root` and `--pillar-root` will not be passed onto salt (see [line 197](https://github.com/mitchellh/packer/blob/master/provisioner/salt-masterless/provisioner.go#L197) in `provisioner.go`).

I believe this is a safe compromise which likely does not break existing functionality.

I will submit a patch for this, and updated docs explaining the interaction between the various salt provisioner config options.

cc @moinfar @SeMeKh

### PR DESCRIPTION
**Pull request by mafrosis**
A few things in this p/r:

- Better path validation
- Dynamic construction of command line args to `highstate`, as discussed in #2652
- The changes I made to fix #2652 are not compatible with #2488 (which fixes #2486) - so I fixed that in a different way - comments please!
- Included another option to set the Salt logging level
- Added tests for most options

### CODE REVIEW

**Comment by mafrosis** [comment]
I'm doing some further work with the salt provisioner, which I'll send in separately. Let me know if there's anything that'll get this merged soon

**Comment by cbednarski** [comment]
Thanks for the PR! I'm planning to include this in `0.9.0` but I don't have a release date scheduled.

**Comment by mafrosis** [comment]
@cbednarski I know you guys are busy at hashiconf right now, but can I get any idea when `0.9.0` will be released onto Atlas? I currently have an issue which is impossible to debug without the `log_level` option.

**Comment by mafrosis** [comment]
@cbednarski Hi! I just noticed there's an 0.9.0-rc1 option for Packer on Atlas under build settings.. Any chance we can get this pull merged so I can test as part of the RC phase?

**Comment by bVector** [comment]
:+1: would love to have this additional flexibility in the next release

**Comment by cbednarski** [comment]
Thanks again for the PR! Please keep an eye open for this in 0.9.

**Comment by mafrosis** [comment]
Awesome! Thanks @cbednarski et al

**Pull request merged**
