### PR TITLE
shell-local port processor

### PR DESCRIPTION
**Pull request by vtolstov**
add shell-local post-processor, closes #2706

### CODE REVIEW

**Comment by vtolstov** [comment]
@cbednarski @rickard-von-essen please, review this, because it very needed and waiting to merge more then 3 months.

**Comment by cbednarski** [comment]
@imduffy15 @vtolstov Thanks for working on this feature, and for your patience in getting it reviewed and merged! I'm sorry to have kept you waiting so long for this one. This is a welcome addition to packer and I know there were be a lot of folks excited about this one. Thanks again!

**Comment by imduffy15** [comment]
Great stuff! Thank you @cbednarski 

It could be cool if it was extended to enable the user to create their own artifact data structure in the packer json to pass down into other post processors.

for example....

```
    [
      {
        "scripts": [
          "./scripts/script-that-converts-vmware-box-to-qemu-format.sh"
        ],
        "artifact": {
              "files": ["box.img"],
              "builderId": "transcend.qemu",
              "state": {
                   "diskName": "box.img"
              }
         }
        "type": "shell-local"
      },
    ]
```

**Comment by cbednarski** [comment]
@imduffy15 Ah the [artifice post-processor](https://www.packer.io/docs/post-processors/artifice.html) can do this. We may need to make some tweaks there but the general feature is there.

**Pull request merged**
