### PR TITLE
builder/virtualbox-iso: disk_variant config

### LINKED ISSUE #4513: Create fixed-size OVA, with virtualbox-iso builder
Hey,
I need to build a fixed size vm for a customer, 
I did my VM using packer, and i see in the go source file that the option is present,
when you create a disk (option is variant), but not in the default builder setup.

I know that I can open and convert the the vmdk inside the OVA.

Would it be nice to have it as a param (variant / disk_size) of the default builder param ?

Guillaume

### PR DESCRIPTION
**Pull request by bi-**
Add disk_variant config option to virtualbox-iso builder.
Closes #4513

### CODE REVIEW

**Comment by mwhooker** [comment]
Awesome, thank you!

Will target this for the next release. Would you mind adding a line to the docs for this new flag? https://github.com/mitchellh/packer/blob/master/website/source/docs/builders/virtualbox-iso.html.md

**Comment by bi-** [comment]
Thank you, I've just updated the documentation.

**Comment by mwhooker** [comment]
👍 lgtm. Will get this in for the next release

**Comment by bi-** [comment]
Actually exposing the --variant flag has no effect on the final image, because VBoxManage export will anyway shrink the image.

**Comment by mwhooker** [comment]
@bi- hmm, interesting. So should we close this?

**Comment by bi-** [comment]
I'm afraid it has no real value this way, maybe better to close/remove it from production.

**Pull request closed without merging**
