### PR TITLE
WinRM

### PR DESCRIPTION
**Pull request by mitchellh**
This overrides #1175 and adds WinRM. It is a mix of @sneal's work as well as @svanharmelen.

The only thing missing from this is the elevated command running. @sneal was that very important? For some reason Terraform doesn't do it and people seem happy but I want to ask, since you put it in Vagrant as well.

### CODE REVIEW

**Comment by mitchellh** [comment]
Going to merge this so I can work on more Windows things. It doesn't change anything existing and is only additive so it can't really break anything that already existed. 

Still looking forward to @sneal's feedback, however!

**Comment by pecigonzalo** [comment]
I know this is closed but elevated was required on https://github.com/packer-community/packer-windows-plugins to install things like SP1 or dotNET. I could test if thats working but i cant find any examples of how to use the winrm communicator for shell(powershell) provisioning.

Also might want to take a look at https://github.com/packer-community/packer-windows-plugins

**Comment by sneal** [comment]
@mitchellh The elevated command wrapper (scheduled win task) is pretty important if you want to do any serious installs on a Windows box. You can workaround it in other ways, but it can be a pain and bites new users who expect scripts to work the same over WinRM as they do via an interactive login session.

I assume Terrform users don't encounter issues like this because they're usually dealing with pre-baked images?

**Comment by mitchellh** [comment]
@sneal I don't think its required anymore since the powershell provisioner has it as an option, so you can do what @pecigonzalo wants to.

**Comment by pecigonzalo** [comment]
You are right, i now see you are including (2243) elevated.go in a similar fashion to the packer-community/packer-windows-plugins implementation and I think it uses the same sort of solution @sneal was using as far as i can tell, so you should be right @mitchellh and this should not be an issue.
I think we can disregard my message here and just make sure this is working on 2243, ill be testing today.

**Comment by tbenade** [comment]
May be unrelated looking for guidance on whether I should open another issue, or it could even be a chocolatey issue. Trying the winrm->amazon-ebs using powershell provisioner.

Packer version 0.8.0, (installed using choco install -y packer -version 0.8.0)
Windows 2012 Server in Parallels.

Running this simple block

```
{
      "type": "powershell",
      "elevated_user": "packer",
      "elevated_password": "packer123!",
      "inline": ["echo 'whoo hoo running elevated'"]
}
```

yields the following.

Exception calling "RegisterTaskDefinition" with "7" argument(s):←[0m
"(12,8):UserId:"←[0m
At C:\Users\Administrator\AppData\Local\Temp\packer-elevated-shell-5595c3b6-f4d←[0m
7-97cc-7dba-12db06cd6b34.ps1:48 char:1←[0m
+ $f.RegisterTaskDefinition($name, $t, 6, "packer", "packer123!", 1, $null) |←[0m
Out- ...←[0m
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~←[0m
~~~←[0m
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException←[0m
+ FullyQualifiedErrorId : ComMethodTargetInvocation←[0m
[0m
Exception calling "GetTask" with "1" argument(s): "The system cannot find the←[0m
file specified. (Exception from HRESULT: 0x80070002)"←[0m
At C:\Users\Administrator\AppData\Local\Temp\packer-elevated-shell-5595c3b6-f4d←[0m
7-97cc-7dba-12db06cd6b34.ps1:49 char:1←[0m
+ $t = $f.GetTask("\$name")←[0m
+ ~~~~~~~~~~~~~~~~~~~~~~~~~←[0m
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException←[0m
+ FullyQualifiedErrorId : ComMethodTargetInvocation←[0m
[0m
Method invocation failed because [System.__ComObject] doesn't contain a method←[0m
named 'Run'.←[0m
At C:\Users\Administrator\AppData\Local\Temp\packer-elevated-shell-5595c3b6-f4d←[0m
7-97cc-7dba-12db06cd6b34.ps1:50 char:1←[0m
+ $t.Run($null) | Out-Null←[0m
+ ~~~~~~~~~~~~~~~~~~~~~~~~←[0m
+ CategoryInfo          : InvalidOperation: (Run:String) [], RuntimeExcept←[0m
ion←[0m
+ FullyQualifiedErrorId : MethodNotFound←[0m
[0m

**Comment by StefanScherer** [comment]
@tbenade try `choco install -y packer -version 0.8.1` - lots of bugfixes for the amazon builder.

**Comment by tbenade** [comment]
Will do thank you.

**Pull request merged**
