### PR TITLE
MS OpenTech packer plugins

### PR DESCRIPTION
**Pull request by v-vlshch**
added: 
   1) builders: azure, hyper-v
   2) provisioners: azure-custom-script-extension, powershell, 
   3) communicators: azureVmCustomScriptExtension, powershell
modified:
   1)  post-processor: vagrant/hyperv.go

### CODE REVIEW

**Comment by jeffmendoza** [comment]
@sethvargo Will we be able to go forward with 1.3 only? Is there anything else of concern?

**Comment by sethvargo** [comment]
I think the next version of packer should target 1.3 and 1.4 or maybe 1.4 totally. Nonetheless, I think dropping 1.2 is acceptable.

**Comment by ducke** [comment]
Any news on this?

**Comment by auroraeosrose** [comment]
Ugh, still sitting after more than six months?

**Comment by mitchellh** [comment]
We're getting close! We've gone from 350 total issues+prs to 250 in the last 2 weeks. We're working our way towards it.

**Comment by mitchellh** [comment]
I'd like to merge this, but it looks pretty out of date. If you want to reopen a PR for the latest I'd take a look, otherwise I can work with the packer-azure repo to try to get that in!

**Comment by marcofranssen** [comment]
Awesome @mitchellh ... Can you give us any statusupdate? I see there are many new releases  since this support has been requested so we must be close to have it in there. 

Maybe a little of topic, is there a release log to see what has been included in the latest releases?

**Comment by cbednarski** [comment]
@marcofranssen You want to look at https://github.com/mitchellh/packer/blob/master/CHANGELOG.md

**Comment by JamieCressey** [comment]
+1

**Comment by erick-thompson** [comment]
Is this PR still outstanding, or has it been superseded?

**Comment by rickard-von-essen** [comment]
@erick-thompson Azure is supported since 0.10.0. Hyper-V is stil not supported.

**Comment by erick-thompson** [comment]
Are there any plans to support Hyper-V?

**Pull request closed without merging**
