### PR TITLE
Adding the ability to skip nat port forwarding for ssh connectivity

### PR DESCRIPTION
**Pull request by pleschev**
Previous PR #980

### CODE REVIEW

**Comment by ColinHebert** [comment]
@rasa @mitchellh Is there any news regarding this pull request?

**Comment by xc8tlik** [comment]
+1 for getting this merged.

**Comment by ColinHebert** [comment]
@rasa is it still okay to go in the next release?

**Comment by saimonmoore** [comment]
what's the status here? Just ran into this. This PR has been open for over a year :scream: ??

**Comment by mitchellh** [comment]
Going to merge this. Thanks!

**Pull request merged**
