### PR TITLE
Use SSH agent when enabled for bastion step

### PR DESCRIPTION
**Pull request by dacamp**
If `!config.SSHDisableAgent` && `SSH_AUTH_SOCK` exists, add the ssh agent as an additional `ssh.AuthMethod` while connecting to the bastion proxy.

I realize there's some overlap here with [communicator/ssh/communicator.go#L326](https://github.com/mitchellh/packer/blob/master/communicator/ssh/communicator.go#L326).  If that's a concern, this function can be moved into the `ssh` package and exported.

I also added some additional `sshBastionConfig` testing.

Thanks!

### CODE REVIEW

**Comment by dacamp** [comment]
[github.com/xanzy/ssh-agent](https://github.com/xanzy/ssh-agent) was used for portability in Terraform [Issue 4323](https://github.com/hashicorp/terraform/pull/4323), so pulled that in.

Alternatively I can check the OS.  Let me know which route you'd prefer.

**Comment by rickard-von-essen** [comment]
Closes #3670

**Comment by rrix** [comment]
Any chance this can make the next minor release?

**Comment by mwhooker** [comment]
thanks!

**Comment by mwhooker** [comment]
hmm, unfortunately this is causing test failures after I rebased. 

```
2017/02/27 18:50:35 [DEBUG] Error fetching SSH_AUTH_SOCK.
--- FAIL: TestSSHAgent (0.15s)
	step_connect_ssh_test.go:43: Socket value: /tmp/ssh-rS992eb43NmN/agent.1384
	step_connect_ssh_test.go:56: Agent PID: 2496
	step_connect_ssh_test.go:78: Want `ssh.AuthMethod`, got `nil`
2017/02/27 18:50:35 [INFO] SSH agent forwarding enabled.
2017/02/27 18:50:35 [DEBUG] Error fetching SSH_AUTH_SOCK.
2017/02/27 18:50:35 [INFO] SSH agent forwarding enabled.
2017/02/27 18:50:35 [DEBUG] Error fetching SSH_AUTH_SOCK.
2017/02/27 18:50:35 [INFO] SSH agent forwarding enabled.
2017/02/27 18:50:35 [DEBUG] Error fetching SSH_AUTH_SOCK.
--- FAIL: TestSSHBastionConfig (0.05s)
	step_connect_ssh_test.go:43: Socket value: /tmp/ssh-ujlEajpcF3zC/agent.2672
	step_connect_ssh_test.go:56: Agent PID: 700
	step_connect_ssh_test.go:43: Socket value: /tmp/ssh-Az4eCITgnY4a/agent.1840
	step_connect_ssh_test.go:56: Agent PID: 568
	step_connect_ssh_test.go:147: want 4 ssh.AuthMethod, got 3 ssh.AuthMethod
2017/02/27 18:50:35 [INFO] communicator disabled, will not connect
FAIL
FAIL	github.com/mitchellh/packer/helper/communicator	0.859s
```


any thoughts? I'm investigating as well

**Comment by mwhooker** [comment]
probably need to get pagent installed with appveyor

**Comment by mwhooker** [comment]
Please see rebased merge in #4598

I had to revert this. Going to leave it closed as it's not complete. Please submit a new PR if you're able to fix the appveyor build

**Comment by dacamp** [comment]
Checkout 5a02614e713c937289c3c1239b0861fbf9bee51c.  Tests pass: https://ci.appveyor.com/project/dacamp/packer/build/10

Is that too weird?  I tweeted to AppVeyor for a suggestion on starting pageant, so this may all be moot.

```diff
commit 5a02614e713c937289c3c1239b0861fbf9bee51c
Author: David Campbell <david@mrcampbell.org>
Date:   Mon Feb 27 13:36:09 2017 -0800

    WIP: run pageant.exe once and only once if windows

diff --git a/helper/communicator/step_connect_ssh_test.go b/helper/communicator/step_connect_ssh_test.go
index 77b8f1b7..107e6fdd 100644
--- a/helper/communicator/step_connect_ssh_test.go
+++ b/helper/communicator/step_connect_ssh_test.go
@@ -5,7 +5,9 @@ import (
 	"os"
 	"os/exec"
 	"path/filepath"
+	"runtime"
 	"strconv"
+	"sync"
 	"testing"
 )
 
@@ -17,6 +19,21 @@ func startAgent(t *testing.T) func() {
 		t.Skip("skipping test due to -short or availability")
 	}
 
+	if runtime.GOOS == "windows" {
+		// only need to start pageant once
+		var once sync.Once
+		once.Do(func() {
+			pageant, err := exec.LookPath("pageant.exe")
+			if err != nil {
+				t.Skip("could not find ssh-agent")
+			}
+			pCmd := exec.Command(pageant)
+			if _, err := pCmd.Output(); err != nil {
+				t.Fatalf("cmd.Output: %v", err)
+			}
+		})
+	}
+
 	bin, err := exec.LookPath("ssh-agent")
 	if err != nil {
 		t.Skip("could not find ssh-agent")

```

**Comment by mwhooker** [comment]
that's pretty weird, but I like it. I don't think sync.Once has any effect since it's local to `startAgent`. Do you think there's any risk of it being run multiple times?

Also I think we should move running pageant.exe to the appveyor build

**Comment by dacamp** [comment]
> Do you think there's any risk of it being run multiple times?

Naw, should only run once.  I could do it within `init` also, but following the other thread, I think reaching out to AppVeyor makes more sense.

**Comment by mwhooker** [comment]
see also #4606

**Pull request closed without merging**
