### PR TITLE
use docker 'exec' instead of 'attach' for remote execution

### PR DESCRIPTION
**Pull request by mariussturm**
Points to discuss for the core team:

  * Is it ok to break backwards compatibility, or should we implement a version check plus fallback to old implementation
  * is /bin/sh the right shell? afaik the old implementation was using bash
  * do we need to cleanup other parts of the code when `attach` is not used anymore

### CODE REVIEW

**Comment by txangel** [comment]
`exec` was added in 1.3 (https://docs.docker.com/v1.3/reference/commandline/cli/).
I'll fork from you and suggest a Backwards-compatible version

**Comment by donaldguy** [comment]
See also #1993

**Comment by kunalkushwaha** [comment]
Hi, 

What is current status of this? Is anyone working on this?

**Comment by babilen** [comment]
It would be quite appreciated if a fix for #1752 could be merged. Is the problem with this PR works only with more recent docker versions?

**Comment by xmik** [comment]
This is fixed by #2150.

**Pull request closed without merging**
