### PR TITLE
Fixes #2743: Change log messages for step_forward_ssh

### LINKED ISSUE #2743: Change log messages for step_forward_ssh
Both **VirtualBox** and **Qemu** builders have a step_forward_ssh, this is somewhat dubious now when there are several ```Communicators```. We should at least update the log messages to not confuse users.

### PR DESCRIPTION
**Pull request by rickard-von-essen**
Changed the log messages and changed the m name of the
VirtualBox builder NAT rule name from packerssh to
packercomm.

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Review please.

**Comment by rickard-von-essen** [comment]
Fixes #2743

**Comment by cbednarski** [comment]
LGTM, thanks for fixing this!

**Comment by pecigonzalo** [comment]
:+1:  We should also stop using the ssh name of the variables eventually.

**Pull request merged**
