### PR TITLE
file provisioner - downloads

### PR DESCRIPTION
**Pull request by 0xBF**
1. communicatior ssh.Download implementation. Only one file without recursion and without preserving file mode.
1. Add "direction" parameter to file provisioner for support file downloading.

no tested very well, but works for me

### CODE REVIEW

**Comment by vtolstov** [comment]
looks fine for me.

**Comment by vtolstov** [comment]
@0xBF scp -vf runs on remote side or in local side?

**Comment by 0xBF** [comment]
on remote side

**Comment by vtolstov** [comment]
@0xBF thanks. If this is merged i can add recursive downloading...

**Comment by gpakosz** [comment]
What would be the milestone for this feature?

This is really interesting, I can already see the light of building Docker **base** images with Packer + Virtualbox provisionner: shell provisioner would tar.xz the rootfs before file provisioner downloads it

**Comment by vtolstov** [comment]
@sethvargo  @jcrosby ping? I think this is very usable and ve can write more provisions that can download files from vm ...

**Comment by vtolstov** [comment]
@gpakosz i need this use-case too.

**Comment by vtolstov** [comment]
@mitchellh please check this.

**Comment by mitchellh** [comment]
LGTM. I'll rebase and merge.

**Comment by mitchellh** [comment]
Merged!

**Comment by vtolstov** [comment]
Thanks!

**Pull request closed without merging**
