### PR TITLE
builder/vmware-esxi: Add step_export

### PR DESCRIPTION
**Pull request by higebu**
Add step_export to builder/vmware-esxi.
Packer exports ovf or ova files from ESXi with ovftool, only if `format` option exists in template.json.
This p-r related to #1577, but doesn't change existing behaviors.

### CODE REVIEW

**Comment by rkarimuthu** [comment]
Is this change merged and available in latest version?

**Comment by rkarimuthu** [comment]
Requirement for "remote_password"  can it be made optional and use an ssh key assumption is the remote build environment ssh keys are shared with ESX host. It will be nice to have this configuration for security reasons.

**Comment by higebu** [comment]
@mitchellh  
Please review and merge this p-r. It's very useful for the people who has many vsphere or vcloud environments.

**Comment by higebu** [comment]
@rasa @sethvargo 

Could you check this p-r?

**Comment by higebu** [comment]
@icnocop 

```
Thank you for this PR.

I just wanted to point out a spelling mistake. The past tense of destroy is destroyed, not destroied.

Thank you. :)
```

Thank you for your review!
I fixed fix the spelling mistake.

```
I'm testing this on Windows 7 Enterprise 64-Bit SP1.

I installed "VMware OVF Tool" to its default location:
C:\Program Files\VMware\VMware OVF Tool

However, this code expects "ovftool.exe" to be in the %PATH%, otherwise I get the following error:
Error ovftool not found: exec: "ovftool": executable file not found in %PATH%

So I'm wondering if this code can be updated to automatically look for it in the default installation directory? Or maybe the path can be specified in the packer template? Otherwise, the documentation should be updated accordingly.

Thank you.
```

I tested on Linux only, so this p-r doesn't support Windows now.
I'll try to support windows.

**Comment by higebu** [comment]
I added support for windows to this feature, and it confirmed by @icnocop.
The details is here: https://github.com/higebu/packer/commit/5481415ca0c122f7cf0caf8a80ef727b05c51ada

I think this p-r is ready to be merged now.

**Comment by jc-asdf** [comment]
I'm having some issues with this patch.  I find that IsDestroyed() isn't working right - it's throwing the following:

==> vmware-iso: Destroying virtual machine...
Build 'vmware-iso' errored: lstat output-vmware-iso: no such file or directory

It also doesn't take into account any customizations to the output_directory command - it's checking for 'output-vmware-iso' no matter where I'm actually outputting the build artifact on the ESX host with the vmware-iso builder.

Looking through the code, I'm wondering if IsDestroyed() should be checking the full path instead of just the d.outputDir?

I'm doing more debugging and hope to find a solution.

**Comment by HeroesDieYoung** [comment]
I'm experiencing the same issue, here is the full output:

```
[root@localhost travis]# ./packer-esx-export/packer build testVM.remote.json
vmware-iso output will be in this color.

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: http://my.url.com/ipxeData/ipxe.iso
==> vmware-iso: Uploading ISO to remote machine...
==> vmware-iso: Creating virtual machine disk
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Registering remote VM...
==> vmware-iso: Starting virtual machine...
    vmware-iso: The VM will be run headless, without a GUI. If you want to
    vmware-iso: view the screen of the VM, connect via VNC without a password to
    vmware-iso: 1.1.1.1:5988
==> vmware-iso: Waiting 10s for boot...
==> vmware-iso: Connecting to VM via VNC
==> vmware-iso: Typing the boot command over VNC...
==> vmware-iso: Waiting for SSH to become available...
==> vmware-iso: Connected to SSH!
==> vmware-iso: Gracefully halting virtual machine...
    vmware-iso: Waiting for VMware to clean up after itself...
==> vmware-iso: Deleting unnecessary VMware files...
    vmware-iso: Deleting: /vmfs/volumes/datastore1/output-vmware-iso/vmware.log
==> vmware-iso: Cleaning VMX prior to finishing up...
    vmware-iso: Unmounting floppy from VMX...
    vmware-iso: Detaching ISO from CD-ROM device...
==> vmware-iso: Compacting the disk image
==> vmware-iso: Exporting virtual machine...
    vmware-iso: Executing: ovftool --noSSLVerify=true --skipManifestCheck -tt=ova vi://user:password@1.1.1.1/packer-enforcer packer-enforcer/packer-enforcer.ova
    vmware-iso: Opening VI source: vi://user@1.1.1.1:443/packer-enforcer
    vmware-iso: Opening OVA target: packer-enforcer/packer-enforcer.ova
    vmware-iso: Writing OVA package: packer-enforcer/packer-enforcer.ova/packer-enforcer.ova
Transfer Completed
    vmware-iso: Completed successfully
    vmware-iso:
==> vmware-iso: Destroying virtual machine...
Build 'vmware-iso' errored: lstat output-vmware-iso: no such file or directory

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: lstat output-vmware-iso: no such file or directory

==> Builds finished but no artifacts were created.
```

My input file (users,passwords,and IPs changed of course)

```
{
  "builders":[{
    "type":"vmware-iso",
    "iso_url":"http://my.url.com/folder/image.iso",
    "iso_checksum":"1180689b067ca7f3b5d4d308b040d500",
    "iso_checksum_type":"md5",
    "ssh_username":"user",
    "ssh_password":"password",
    "ssh_wait_timeout":"30m",
    "shutdown_command":"poweroff",
    "guest_os_type":"centos-64",
    "vm_name":"packer-enforcer",
    "vmx_data":{
      "memsize":"16384",
      "numvcpus":"8",
      "cpuid.coresPerSocket":"4",
      "ethernet0.present":"TRUE",
      "ethernet0.virtualDev":"e1000",
      "ethernet0.networkName":"Packer Network",
      "ethernet0.addressType":"generated"
    },
    "headless":"true",
    "remote_type":"esx5",
    "remote_username":"user",
    "remote_password":"password",
    "remote_host":"1.1.1.1",
    "remote_datastore":"datastore1",
    "format":"ova"
  }]
}
```

**Comment by higebu** [comment]
@jc-asdf @HeroesDieYoung 

Thank you for testing and sorry for the delay.
I fixed 'output-vmware-iso' issue. Please check it, when you have a time.

**Comment by higebu** [comment]
Development builds are here: https://github.com/higebu/packer/releases/tag/0.8.1-dev.higebu1

**Comment by leroux** [comment]
@higebu, it seems that your development builds at https://github.com/higebu/packer/releases/tag/0.8.1-dev.higebu1 are not based off of tag 0.8.1-dev.higebu1.

I get the following error when running the binaries from your build:

```
* unknown configuration key: "format"
2015/07/07 20:39:56 ui error: 1 error(s) occurred:

* unknown configuration key: "format"
2015/07/07 20:39:56 waiting for all plugin processes to complete...
1 error(s) occurred:
2015/07/07 20:39:56 /home/vadmin/packer_higebu-0.8.1-dev/packer-provisioner-shell: plugin process exited

2015/07/07 20:39:56 /home/vadmin/packer_higebu-0.8.1-dev/packer-provisioner-shell: plugin process exited
2015/07/07 20:39:56 /home/vadmin/packer_higebu-0.8.1-dev/packer-builder-vmware-iso: plugin process exited
* unknown configuration key: "format"
```

It works when I build it though.

**Comment by higebu** [comment]
@lalyos 
Thank you for testing. I'll check my builds.

**Comment by higebu** [comment]
@lalyos 
I fixed my builds.
Thanks!

**Comment by ajbouh** [comment]
Just confirmed that the conflict here is very minor (markdown formatting and indentation) in website documentation. Any way I can help get this merged?

**Comment by leroux** [comment]
I used the patch from this PR for a bit and got weirdness with how the files were output. The output files would be at `output-packer-ubuntu/output-packer-ubuntu/output-packer-ubuntu.ova` or something along those lines instead of the artifacts being under a single output directory.

**Comment by BigAl** [comment]
Does any more work need to be done on this? I'd be keen to have this feature and happy help..

**Comment by icnocop** [comment]
@mitchellh or @cbednarski , can you help merge this PR please?

Thank you.

**Comment by epowell** [comment]
I'm currently working around this issue with some terrible shell-local provisioner scripts. Would be very happy to have this feature.

**Comment by Sher-Chowdhury** [comment]
Me too! I would really like to have this feature asap. At the moment I keep getting an orphaned vm at the end of build process. 

In the mean time is there a workaround I can use to remotely build my mahchines on ESXi?

**Comment by epowell** [comment]
@Sher-Chowdhury I'm using this command on the ESXi host to re-register the VM: 
`vim-cmd solo/registervm '/vmfs/volumes/datatstore1/vm_dir/vm.vmx' VM`

There are also API clients that can perform the register operation.

**Comment by higebu** [comment]
@markpeek Could you review this PR? I rebased this to master.

**Comment by epowell** [comment]
@Sher-Chowdhury Sorry, got my issues mixed up. :)

Here's what I use to export an OVA at the end of the build process:

```
{
  "type": "shell-local",
  "command": "mkdir -p output && ovftool --powerOffSource --overwrite --noSSLVerify --noImageFiles 'vi://{{user `remote_username`}}:{{user `remote_password`}}@{{user `remote_host`}}/{{user `vm_name`}}' output/{{user `vm_name`}}.ova"
},
{
  "type": "shell-local",
  "command": "vim-cmd vmsvc/power.on `vim-cmd vmsvc/getallvms | grep '\\[{{user `remote_datastore`}}\\] {{user `output_directory`}}/{{user `vm_name`}}.vmx' | cut -d' ' -f 1`",
  "execute_command": ["sshpass", "-p", "{{user `remote_password`}}", "ssh", "-o", "StrictHostKeyChecking no", "-o", "UserKnownHostsFile /dev/null", "{{user `remote_username`}}@{{user `remote_host`}}", "{{.Command}}"]
}
```

The first command is the important one, but if you leave the VM powered off, Packer will consider the build failed. So I power the VM back on. This requires sshpass in your Packer build environment, and a tolerance for calling things insecurely on the command line.

**Comment by Sher-Chowdhury** [comment]
@epowell 

Thank you for your suggestion. However for security reasons, I think we'll get in trouble taking this approach.

**Comment by markpeek** [comment]
@higebu Thank you for adding this feature to packer. I did add some validation/tests (https://github.com/mitchellh/packer/commit/9d0c443ca25fcb58f77a08e4a0a2980da2f75f82) and obscured the password in the ovftool logging (https://github.com/mitchellh/packer/commit/0d2fa223f2315ce80d2f841f25a67cd24971ab0b) Could you review these changes?

**Comment by higebu** [comment]
@markpeek LGTM! Thank you very much for merging, adding tests and support for hiding password!

**Comment by Sher-Chowdhury** [comment]
So excited! Can't wait to try this out :+1:

**Comment by rikardq** [comment]
Yes  excited! good work :+1:

**Comment by ramiabughazaleh** [comment]
@leroux, for reference, regarding the output directory issue, there's a follow up issue here: https://github.com/mitchellh/packer/issues/3896

**Pull request merged**
