### PR TITLE
builder/vmware-iso: set ovftool output path

### LINKED ISSUE #3896: Feature request: Define output directory for the exported virtual machine
Since my Go coding skills are limitted, I would like to ask you guys for a new feature. In the vmware builder, there is an option (format) to export the VM to your local machine. Currently it outputs the OVA, or OVF in the base directory, but I would like to define the output folder in the JSON, e.g. "format_output_dir": "./OVA". Is this possible to make?

### PR DESCRIPTION
**Pull request by mwhooker**
Closes #3896

### CODE REVIEW

**Comment by mwhooker** [comment]
untested. Would be great if someone could help test

**Comment by mwhooker** [comment]
Looks like there's a thing in fusion to emulate this. will check that out latest if no one has tested this

**Comment by spmiller** [comment]
I've tested this fix, and it doesn't result in quite what I expected. If I define
```
{
  "type": "vmware-iso",
  "output_directory": "output/vmware",
  "vm_name": "my_vm",
  "format": "ova",
  ...
}
```

I would expect the resulting VM to exist at `output/vmware/my_vm.ova`. Instead I get `my_vm/my_vm.ova/my_vm.ova`

Log message for posterity:

> vmware-iso: Executing: ovftool.exe --noSSLVerify=true --skipManifestCheck -tt=ova vi://root:****@myEsxServer.domain/my_vm my_vm\my_vm.ova

The iso builder explicitly ignores the `output_directory` parameter on remote builds. I made some changes to fix this; these can be seen [here](https://github.com/mitchellh/packer/compare/master...spmiller:vmware-output-dir?expand=1).

I haven't submitted a pull request for this because these changes leaves an empty directory lying around on the ESXi server (` /vmfs/volumes/datastore1/my_vm` in my case) which causes subsequent builds to abort. Presumably this is why the code to disregard `output_directory` was added in the first place.

**Comment by spmiller** [comment]
The remote builder not respecting the output directory is tracked in #4051

**Comment by jimmythedog** [comment]
I've just tested this, and I don't think it's working, as the ova ended up in the $vm-name directory:
`2017/02/23 14:02:39 ui:     vmware-iso: Executing: ovftool --noSSLVerify=true --skipManifestCheck -tt=ova vi://user:****@engtest74/centos7-x86_64-dev-SNAPSHOT centos7-x86_64-dev-SNAPSHOT/centos7-x86_64-dev-SNAPSHOT.ova`

I wonder if it's due to this block: https://github.com/mitchellh/packer/blob/ovfexportpath/builder/vmware/iso/builder.go#L202 ?

I have remote_type="esx5" and format="ova" so the above block would set config.OutputDir to the VMName?

Then https://github.com/mitchellh/packer/blob/ovfexportpath/builder/vmware/iso/step_export.go#L62 uses config.OutputDir which, of course, is the VMName

I could be wrong in my analysis, as I'm no Go expert, so please forgive me if I'm talking thru my ....

Please feel free to ask me to retest, if required

**Comment by jimmythedog** [comment]
OK, I'm going to try and help out on this one, but being no `go` expert, please be gentle!!!

I've created a [pull request](https://github.com/mitchellh/packer/pull/4592) and it seems to work for me

**Pull request closed without merging**
