### PR TITLE
common: two minor fixes

### PR DESCRIPTION
**Pull request by josharian**

### CODE REVIEW

**Comment by kelseyhightower** [comment]
@josharian I'm rerunning the tests on this one, other than that LGTM.

**Comment by kelseyhightower** [comment]
Looks like the tests are failing because of:

```
google.golang.org/cloud/compute/metadata
../../../google.golang.org/cloud/compute/metadata/metadata.go:54: unknown net.Dialer field 'KeepAlive' in struct
```

This is also the case for other PRs. We only see this issue with testing running on Golang 1.2

**Comment by josharian** [comment]
@kelseyhightower you're everywhere! Nice to see you here. :) Are you a hashicorper now?

Are you going to start working through the packer PR backlog? That would be most welcome--I'd start sending more! (How about #2018, for some easy, helpful pickings? code.google.com is going away soon, so it has to happen anyway.)


> This is also the case for other PRs. We only see this issue with testing running on Golang 1.2

That's because of this: https://github.com/GoogleCloudPlatform/gcloud-golang/commit/de1c38e5af44da22abe7c3b14a1edcf6264dae55

I think that the right fix is to drop Go 1.2 support in Packer.

The alternative, which is also independently a good idea, is to vendor Packer's dependencies. (This would also prevent make dev from hitting the network every time, which is just silly/annoying. I have it commented out in a series of local patches I'm carrying around as I work.) You could then vendor a commit prior to that one, if you wanted. That said, I still think that requiring Go 1.3+ (or Go 1.4+!) is a better choice.

**Comment by sethvargo** [comment]
I think we are going to drop 1.2 support and require 1.4 going forward.

**Comment by mitchellh** [comment]
LGTM!

**Comment by sbarnden** [comment]
Removing the workaround for issue #5927 causes an issue when building on windows.

When trying to build from master after this workaround was removed:
2015/06/13 13:58:46 ui:     virtualbox: Downloading or copying: file://C:/PackerBuild/V52218-01.iso
2015/06/13 13:58:46 packer-builder-virtualbox-iso.exe: 2015/06/13 13:58:46 Acquiring lock to download: file://C:/PackerBuild/V52218-01.iso
2015/06/13 13:58:46 packer-builder-virtualbox-iso.exe: 2015/06/13 13:58:46 Parsed URL: &url.URL{Scheme:"file", Opaque:"", User:(*url.Userinfo)(nil), Host:"C:", Path:"/PackerBuild/V52218-01.iso", RawQuery:"", Fragment:""}
2015/06/13 13:58:46 ui:     virtualbox: Error downloading: open PackerBuild/V52218-01.iso: The system cannot find the path specified.

By re-inserting the workaround:
2015/06/13 14:09:42 ui:     virtualbox: Downloading or copying: file:///C:/PackerBuild/V52218-01.iso
2015/06/13 14:09:42 packer-builder-virtualbox-iso.exe: 2015/06/13 14:09:42 Acquiring lock to download: file:///C:/PackerBuild/V52218-01.iso
2015/06/13 14:09:42 packer-builder-virtualbox-iso.exe: 2015/06/13 14:09:42 Parsed URL: &url.URL{Scheme:"file", Opaque:"", User:(*url.Userinfo)(nil), Host:"", Path:"/C:/PackerBuild/V52218-01.iso", RawQuery:"", Fragment:""}
2015/06/13 14:09:42 packer-builder-virtualbox-iso.exe: 2015/06/13 14:09:42 Verifying checksum of C:/PackerBuild/V52218-01.iso

Compiled code for the test on:
[developer@localhost packer]$ go version
go version go1.4.2 linux/amd64

Building a VM with virtualbox-iso builder.

**Comment by mitchellh** [comment]
@sbarnden Just added it back, I don't see any harm doing so. Thanks!

**Comment by josharian** [comment]
@sbarnden @mitchellh worth also reporting upstream?

**Comment by mitchellh** [comment]
@josharian If I remember correctly, I think I did, and I think it was closed as invalid. Its fine. :) We'll keep it in there.

**Pull request merged**
