### PR TITLE
Make configuration of vsphere post processor more flexible.

### PR DESCRIPTION
**Pull request by rylarson**
To address this issue: https://github.com/mitchellh/packer/issues/1851

I tested this deploying to vsphere 5.5 w/ no Resource Pools and vsphere 5.1 with resource pools. It works for both.

A previous commit (https://github.com/mitchellh/packer/commit/f61cc3f99c1819f985a0f401f1871a5c64b1f425#diff-241aa797e0799055d0d49957ec5dce23) that added a trailing `'/'` to the vi target uri broke the hack where setting `resource_pool = " "` would make the upload succeed for deployments that were not licensed for DRS (or just don't have any resource pools).

This just makes the configuration more flexible so it works for deployments with and without resource pools. I have contributed a lot to [vagrant-vsphere] (https://github.com/nsidc/vagrant-vsphere) and found that for tools that interface with vsphere, the best policy is to be as flexible as possible and output good error messages, which ovftool does. Because every vmware infrastructure deployment is different, this can't possibly be tested on every combination of version and licensing.

**Details**
   * When a `resource_pool` **is not** specified, a `datastore` is required, and when a `resource_pool` **is** specified, a `datastore` is optional.
      * I chose to just make resource pool and data store optional, ovftool gives great error output and it will be immediately apparent to the user what is going on if they screw up the configuration somehow.
   * Also made `diskmode` optional since ovftool defaults to thick on its own.

### CODE REVIEW

**Comment by rylarson** [comment]
Bump, is there anything else you guys need from me for this to be merged?

**Comment by aogail** [comment]
+1 - this causes me problems, too

**Comment by tfhartmann** [comment]
+1 Me as well, is there a work around?

**Comment by FlxPeters** [comment]
+1 - I really need this. How can i patch it in my packer(installed via homebrew on Mac)

**Comment by rylarson** [comment]
Bump again. I don't know that I would consider this an enhancement. Commit f61cc3f introduced a bug but mostly because the previous configuration mechanism was broken (i.e. setting resource pool to " " and depending on the fact that ovftool took a URI with a trailing space).

I would be happy to do whatever additional testing needs to be done to get this merged.

**Comment by bemeyert** [comment]
/me bumps too
Packerfolks: Is there anybody out there...?

**Comment by mitchellh** [comment]
LGTM!

**Comment by mitchellh** [comment]
I'll update the docs manually.

**Comment by mitchellh** [comment]
Merged

**Comment by rylarson** [comment]
I see the comment says merged but the PR was closed as unmerged.

Ryan

**Comment by mitchellh** [comment]
It was merged via commit, not via merge button

**Pull request closed without merging**
