### PR TITLE
Adds passwords for VNC on VMWare builders

### PR DESCRIPTION
**Pull request by israelshirk**
It's getting harder and harder to find new memes these days...

Depends on mitchellh/go-vnc#18; tested on ESXi 5.5 and Fusion 7.

### CODE REVIEW

**Comment by mitchellh** [comment]
This looks great, but I'm going to skip on it for 0.8.1 to avoid any risk of breaking builds.

**Comment by cbednarski** [comment]
Thanks for the PR! Unfortunately I have not had a chance to test this yet so I am going to defer this until after 0.9.0.

**Comment by rickard-von-essen** [comment]
This stops ESXi 6.0 with _Embedded Host Client_ from displaying the console. The miniature preview still works. Add an option to disable VNC password.

**Comment by israelshirk** [comment]
I'm no longer in need of this - switched to greener grass.  We were in a pretty heavily-regulated environment, so having passwords for network services was a huge must (unless you were the security guy!)...  The guys there would probably really appreciate a forwards-compatible solution though.

**Comment by rickard-von-essen** [comment]
Merged in f961ce701b9ee

**Pull request closed without merging**
