### PR TITLE
builder/amazon-chroot: various fixing and debugging of chroot builder

### PR DESCRIPTION
**Pull request by catsby**
WIP

### CODE REVIEW

**Comment by mitchellh** [comment]
Good catches! So far so good.

**Comment by mitchellh** [comment]
LGTM!

**Comment by catsby** [comment]
5d2ea08 should fix #865 , you can now specify a `root_volume_size` config var (must be larger than the current root volume size):

```javascript
{
  "builders": [
    {
      "type": "amazon-chroot",
      "region": "us-west-2",
      "source_ami": "ami-dfc39aef",
      "ami_name": "packer-chrooting-{{timestamp}}",
      "root_volume_size": 12
    }
  ]
}
```

**Comment by flyinprogrammer** [comment]
```
"root_volume_size": "{{user `volume_size`}}"
```

yields:
```
cannot parse 'root_volume_size' as int: strconv.ParseInt: parsing "": invalid syntax
```

did anyone try testing this?

**Comment by cbednarski** [comment]
@flyinprogrammer This is likely not covered by our integration tests. Can you open a new issue for this?

**Pull request merged**
