### PR TITLE
unbreak glob pattern in floppy_files

### LINKED ISSUE #4178: "floppy_files" with wildcard characters are not working properly in qemu builder
Hello.

It looks like there is a bug in Packer 0.11 and 0.12 when using the floppy_files with wildcards.
It's not happening in version 0.10 - with this version it's working fine like it's in the documentation: https://www.packer.io/docs/builders/qemu.html#floppy_files

When I'm using "floppy_files" like this:

```
      "floppy_files": [
        "/var/tmp/del/NetKVM/w10/amd64/netkvm*.cat"
      ]
```

I'm getting this error:

```
* Bad Floppy disk file '/var/tmp/del/NetKVM/w10/amd64/netkvm*.cat': stat /var/tmp/del/NetKVM/w10/amd64/netkvm*.cat: no such file or directory
```

FOR BUGS:
- Packer version: Packer v0.11.0 and Packer v0.12.0
- Host platform: Fedora 23
- Debug log output from `PACKER_LOG=1 packer build template.json`: https://gist.github.com/ruzickap/9dddefef90bf28b927916dd1f31efa93
- The _simplest example template and scripts_ needed to reproduce the bug.
```
  "builders":
  [
    {
......
      "type": "qemu",
......
      "floppy_files": [
        "/var/tmp/del/NetKVM/w10/amd64/netkvm*.cat"
      ]
    }
  ],
```

Thank you for looking at it...

### PR DESCRIPTION
**Pull request by vtolstov**
fix glob patterns in `floppy_files`

Closes #4178

Signed-off-by: Vasiliy Tolstov v.tolstov@selfip.ru

### CODE REVIEW

**Comment by vtolstov** [comment]
@rickard-von-essen can you check this? Also note that test failure may not be because of this patch.

**Comment by rickard-von-essen** [comment]
Could you give a simple example of what this fixes?

**Comment by rickard-von-essen** [comment]
Could you also review the test failure.

**Comment by vtolstov** [comment]
@rickard-von-essen @mwhooker i'm fix tests.

**Comment by mwhooker** [comment]
I think this looks good to me.

I did a quick scan of the docs and saw that `floppy_files` is documented differently almost everywhere. We'll want to make sure the docs get sync'd to the correct behavior.

`git grep -A9 -B1 "\`floppy_files\`" website/source/docs/`


I also noticed this wording in the docs:

`Directory names are also allowed, which will add all the files found in the directory to the floppy.`

which I don't think reflects current behavior

**Comment by rickard-von-essen** [comment]
Fixed the docs.

**Comment by rickard-von-essen** [comment]
> Directory names are also allowed, which will add all the files found in the directory to the floppy.

Sorry missed this. Isn't that how it works now?

**Comment by mwhooker** [comment]
@rickard-von-essen oh I think you're right. Was thinking os.stat only worked on files, but was mistaken

**Pull request merged**
