### PR TITLE
Include functionality with simple syntax

### PR DESCRIPTION
**Pull request by dieu**
```
{
    "include": {
        "<path_to_file>": [
             "<type_of_component>[<name_or_index_or_'*'_of_component>]"
        ]
    }
}
```

### CODE REVIEW

**Comment by dieu** [comment]
@markpeek can you look on it? :)

**Comment by dieu** [comment]
@cbednarski can you look and give your feedback?)

**Comment by vtolstov** [comment]
i thinks this is very useful, for example in my case i have custom builder section, but identical provisioner and post-processor. So in my case of 30-50 packer templates this case save some time when i need to add provisioner or post-processor to all of them.

**Comment by dieu** [comment]
@vtolstov Yeh, we have also many cases when will be great to have ability to reuse a part of another json manifest.

it's first simple implementation, also I thought about ability to have reference on link (git/https).

**Comment by mwhooker** [comment]
Thanks very much for the PR. I could see how this might be very useful.

I don't think that we'll be merging this in before our 1.0 release, however. After 1.0 we want to change up our config syntax, including possibly moving to HCL as the templating language. This type of idea should definitely be revisited then.

**Pull request closed without merging**
