### PR TITLE
Fix boot command key output repetition

### PR DESCRIPTION
**Pull request by suma**
In my colleague's environment, boot_command outputs redundant letters so it fails to progress.
virtualbox-iso builder executes VBoxManage `keyboardputscancode` each 1-byte scancode, it causes redundant key output when each VBoxManage execution has too long interval. This interval depends machine specs which running packer.
This PR makes `keyboardscancode` output scancodes all at once each character in boot_command.

### CODE REVIEW

**Comment by grv87** [comment]
I confirm that the bug exists. Packer sends `boot_command` like `/iiiiiinstall/vmlinuz ...`.

Host OS Windows 7 SP1 x64, Packer 0.7.5, VirtualBox 4.3.28.

**Comment by rickard-von-essen** [comment]
Actually this is kind of not a bug. The problem is that the boot command is typed by entering key code into the keyboard buffer. If they are sent to fast keystrokes will be lost, if they are sent to slow characters will be repeated. Regardless of that this PR might improve the reliability, but it is very hard to verify it.

**Comment by mitchellh** [comment]
I agree with @rickard-von-essen.

I understand this issue now, but I'm not sure the best way to fix it. I think perhaps adding a setting externally for how long to hold the keycode for... but even so it really is VirtualBox sending it. This is a weird thing that I think VirtualBox should perhaps address on their own since they ultimately can view timing as it relates to the guest OS.

**Comment by grv87** [comment]
I agree that this problem is too hard to detect and fix. Right solution is, of course, to upgrade machine running packer.

For the record, as a workaround I enable video capture and watch recorded video to see what actually was typed.
So it is not fully automatic way.

Also I'll try to move to Linux since it looks like Windows-only problem.

**Pull request closed without merging**
