### PR TITLE
Add EBS snapshot tags #846 #1219

### LINKED ISSUE #846: Add ability to apply tags to an AMI's ELB snapshot
The amazon-ebs provisioner already has a feature to apply tags to the images packer produces, but it does not apply tags to the ELB snapshot which is produced alongside the AMI.

A provisioner option "snapshot_tags" or similar would be useful to help organise snapshots within an account - especially as snapshots are not deleted with their dependent AMIs.

### PR DESCRIPTION
**Pull request by catsby**
Take #1219 and update for new AWS SDK.
Also fixes hidden bug in applying tags, where only the latest of the tags gets applied.

Fixes #846

### CODE REVIEW

**Comment by mitchellh** [comment]
We don't use the BATS tests anymore, can you just update to use the Go acceptance framework? Otherwise LGTM.

**Comment by catsby** [comment]
> can you just update to use the Go acceptance framework?

SGTM, will do in the AM

**Comment by catsby** [comment]
Updated with acc test

**Comment by mitchellh** [comment]
LGTM!

**Comment by Jackyjjc** [comment]
My team's project is waiting on this one, any update on when is this gonna get merged?

**Comment by catsby** [comment]
@Jackyjjc Just merged :smile:

**Comment by Jackyjjc** [comment]
@catsby Thank you! What is the release process like? When would this get into a release?

**Pull request merged**
