### PR TITLE
Remove deprecated parallels_tools_host_path and guest_os_distribution

### PR DESCRIPTION
**Pull request by rickard-von-essen**
Remove deprecated and unused option ```parallels_tools_host_path```.
Remove deprecated ```guest_os_distribution``` changing it to ```guest_os_type```.

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
@legal90 review please.
Do you think this is the correct way of migrating ```guest_os_distribution```?

**Comment by legal90** [comment]
@rickard-von-essen It looks good to me. :+1: 
> Do you think this is the correct way of migrating guest_os_distribution?

Yes, it is correct.

**Comment by cbednarski** [comment]
LGTM; just needs a merge conflict resolved.

**Comment by rickard-von-essen** [comment]
Fixed the merge conflict. @cbednarski I leave it for you to merge since you have it assigned.

**Comment by rickard-von-essen** [comment]
FYI: this will introduce a backwards incompatible change which requires you to run ```packer fix...``` if you have ```parallels_tools_host_path``` or ```guest_os_distribution``` in your template, which I guess not many have but it's worth noting in the change log.

**Comment by cbednarski** [comment]
@rickard-von-essen Thanks! I will make sure to note the BC change in the changelog.

**Pull request merged**
