### PR TITLE
Save the generated SSH key as a file in debug mode

### PR DESCRIPTION
**Pull request by ColinHebert**
Based on the code in the AWS builder.

### CODE REVIEW

**Comment by ColinHebert** [comment]
Any feedback on this PR?

**Comment by vtolstov** [comment]
I thinks that its nice feature, it can helps to debug provision issue in DO, @sethvargo does it possible to include this?

**Comment by ColinHebert** [comment]
Waiting for some feedback

**Comment by sethvargo** [comment]
This seems reasonable to me, although it would be great to see a test for this.

**Comment by ColinHebert** [comment]
@sethvargo same problem as mentioned in #1831, I wouldn't mind improving existing tests (really any change should have broken existing tests), but it seems that what needs to happen here is defining how those tests work. Someone with more experience with Go and a clearer idea of how unit tests are working in Go would be more qualified. (Seriously I looked at the existing tests and tried to have a similar behaviour but the current tests available do not make much sense to me).

**Comment by einarf** [comment]
That's pretty much a copy-paste from the openstack builders, so should be perfectly fine.

**Comment by mitchellh** [comment]
LGTM!

**Pull request merged**
