### PR TITLE
make fmt

### PR DESCRIPTION
**Pull request by dacamp**
- `gofmt` simplify and write to source

### CODE REVIEW

**Comment by dacamp** [comment]
This should prevent a8e57d8 from happening again.

**Comment by rickard-von-essen** [comment]
👍

**Comment by rickard-von-essen** [comment]
@mwhooker We should enforce formatting.

**Comment by dacamp** [comment]
Wait what?!  Ahhh man! Lamest rebase ever...  I'm not even sure WTF just happened.  Going to try once again to rebase upstream, otherwise I'll just reopen.   Sorry! 😞

**Comment by dacamp** [comment]
Good grief... Sorry about that guys!  I've just made the Makefile change.  Probably would be better for the committer to run `make fmt` before landing anyways.  Otherwise, nearly every commit before this lands may create some type of conflict otherwise.

**Comment by mwhooker** [comment]
Agreed. Will think of the best way to do it. Maybe we can make a unit test
fail if it's not formatted. I haven't had much luck with git precommit
hooks, but that's another option

**Comment by mwhooker** [comment]
I think what I'll do is make a test that fails if there're files not go-fmt'd. I'm not sure running fmt on `make test` will provide enough of a guarantee.

**Comment by mwhooker** [comment]
had to rewrite the fmt target because it was still formatting vendored files. I think because it was finding the root package in `go list`

**Pull request merged**
