### PR TITLE
Update winrm / winrmcp

### LINKED ISSUE #4412: update winrmcp library
There's a a [commit to the library](https://github.com/packer-community/winrmcp/pull/10) which might help us. This issue https://github.com/packer-community/winrmcp/issues/9 describes an out of memory exception when uploading large files. It's been fixed and I believe it may help with some of the issues we've been seeing:

* This one I don't believe is because of it, but the comments mention the issue: #4203 
* closes #2921
* possibly #3007 though this one may already be fixed

There is also a new error which I've reported [here](https://github.com/packer-community/winrmcp/pull/21)

* closes #3286
* #4390 (dupe)

This has been merged so we can reference the new version

### PR DESCRIPTION
**Pull request by EikeVerdenhalven**
Here I am updating packer to be in line with the current development on winrm / winrmcp. Winrmcp fixes an issue where win7 machines randomly aborts file uploads via WinRM due to memory starvation.
Due to interface changes in winrm, the azure implementation needed to be updated. Though the unit tests are fine, the author does not have the resources to run the acceptance tests :(.

closes #4412

### CODE REVIEW

**Comment by mwhooker** [comment]
you're a mensch! I'm actually half way through this exact thing right now, but this is a life saver

**Comment by mwhooker** [comment]
one thing is I'm going to update the `winrm/soap` library.

**Comment by mwhooker** [comment]
closes #

**Comment by EikeVerdenhalven** [comment]
You're welcome :-) 
Just be aware, that though I've tried to be diligent it's not tested yet. My original intention was to fix the Win7 upload issue (which is wrecking my nerves...). Just managed to get through the code ripples that followed.

**Pull request merged**
