### PR TITLE
Add support for Windows to Azure.

### LINKED ISSUE #3389: azure-arm driver doesn't clean up after itself when interrupted
Packer version 0.10.0
Driver: azure-arm

I interrupted a packer build on azure-arm after realizing it was stuck in a script (my fault), and it didn't clean up the resources it created, despite saying it did. Packer output:

<pre>
azure-arm output will be in this color.

==> azure-arm: Preparing builder ...
    azure-arm: Creating Azure Resource Manager (ARM) client ...
==> azure-arm: Creating resource group ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-v4lwhnbt24'
==> azure-arm:  -> Location          : 'Central US'
==> azure-arm: Validating deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-v4lwhnbt24'
==> azure-arm:  -> DeploymentName    : 'pkrdpv4lwhnbt24'
==> azure-arm: Deploying deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-v4lwhnbt24'
==> azure-arm:  -> DeploymentName    : 'pkrdpv4lwhnbt24'
==> azure-arm: Getting the public IP address ...
==> azure-arm:  -> ResourceGroupName   : 'packer-Resource-Group-v4lwhnbt24'
==> azure-arm:  -> PublicIPAddressName : 'packerPublicIP'
==> azure-arm:  -> SSHHost             : '40.83.17.186'
==> azure-arm: Waiting for SSH to become available...
==> azure-arm: Connected to SSH!
==> azure-arm: Provisioning with shell script: scripts/base.sh
    azure-arm: **** PACKER_BUILDER_TYPE is azure-arm ****
    azure-arm: **** ROLE is compute ****
    azure-arm:
    azure-arm: We trust you have received the usual lecture from the local System
    azure-arm: Administrator. It usually boils down to these three things:
    azure-arm:
    azure-arm: #1) Respect the privacy of others.
    azure-arm: #2) Think before you type.
    azure-arm: #3) With great power comes great responsibility.
    azure-arm:
^CBuild 'azure-arm' errored: Build was cancelled.
Cleanly cancelled builds after being interrupted.
</pre>

Azure resources view:

<pre>
$ azure resource list |grep packer
data:    /subscriptions/XXXXX/resourceGroups/packer-Resource-Group-v4lwhnbt24/providers/Microsoft.Compute/virtualMachines/pkrvmv4lwhnbt24                                    pkrvmv4lwhnbt24                           packer-Resource-Group-v4lwhnbt24  Microsoft.Compute/virtualMachines                                                centralus   null                                                                                                                                                                                                                                                                         
data:    /subscriptions/XXXXX/resourceGroups/packer-Resource-Group-v4lwhnbt24/providers/Microsoft.Network/networkInterfaces/packerNic                                        packerNic                                 packer-Resource-Group-v4lwhnbt24  Microsoft.Network/networkInterfaces                                              centralus   null                                                                                                                                                                                                                                                                         
data:    /subscriptions/XXXXX/resourceGroups/packer-Resource-Group-v4lwhnbt24/providers/Microsoft.Network/publicIPAddresses/packerPublicIP                                   packerPublicIP                            packer-Resource-Group-v4lwhnbt24  Microsoft.Network/publicIPAddresses                                              centralus   null                                                                                                                                                                                                                                                                         
data:    /subscriptions/XXXXX/resourceGroups/packer-Resource-Group-v4lwhnbt24/providers/Microsoft.Network/virtualNetworks/packerNetwork                                      packerNetwork                             packer-Resource-Group-v4lwhnbt24  Microsoft.Network/virtualNetworks                                                centralus   null
</pre>

### LINKED ISSUE #3456: Build 'azure-arm' errored: unexpected EOF
- Packer Version: 0.10.0
- Host platform: OS X 10.11.3
- Crash log from `packer build -only=azure-arm template.json`:
https://gist.github.com/rarsan/76fd0c0033844e5067466d26fb07e933

Snippet:
```
2016/04/18 18:21:25 packer: 	/private/tmp/packer20160405-28622-29ix7y/src/github.com/mitchellh/packer/builder/azure/arm/builder.go:90 +0xcb9
2016/04/18 18:21:25 packer: github.com/mitchellh/packer/packer/rpc.(*BuilderServer).Run(0xc820246820, 0x1, 0xc8202d4540, 0x0, 0x0)
2016/04/18 18:21:25 packer: 	/private/tmp/packer20160405-28622-29ix7y/src/github.com/mitchellh/packer/packer/rpc/builder.go:93 +0x3b9
2016/04/18 18:21:25 packer: reflect.Value.call(0xd8d720, 0xefc0b8, 0x13, 0x10d2438, 0x4, 0xc82061fed8, 0x3, 0x3, 0x0, 0x0, ...)
2016/04/18 18:21:25 packer: 	/usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:435 +0x120d
2016/04/18 18:21:25 packer: reflect.Value.Call(0xd8d720, 0xefc0b8, 0x13, 0xc82061fed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/04/18 18:21:25 packer: 	/usr/local/Cellar/go/1.6/libexec/src/reflect/value.go:303 +0xb1
2016/04/18 18:21:25 packer: net/rpc.(*service).call(0xc820143e00, 0xc820143dc0, 0xc8202415b8, 0xc82014b100, 0xc820246b00, 0xbe44c0, 0xc8202d44ec, 0x18a, 0xbad340, 0xc8202d4540, ...)
2016/04/18 18:21:25 packer: 	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:383 +0x1c2
2016/04/18 18:21:25 packer: created by net/rpc.(*Server).ServeCodec
2016/04/18 18:21:25 packer: 	/usr/local/Cellar/go/1.6/libexec/src/net/rpc/server.go:477 +0x49d
2016/04/18 18:21:25 ui error: Build 'azure-arm' errored: unexpected EOF
```

### PR DESCRIPTION
**Pull request by boumenot**
This is last merge that will happen from the github.com/Azure/packer-Azure
repository.  All development is being over to this repository.

The biggest change in this merge is support for Windows.  There are a few other
fixes as well.

 * If the user cancels the build, clean up any resources.
 * Output a reasonable build artifact.
 * Log requests and responses with Azure.
 * Support for US Government and the China clouds.
 * Support interrupting long running tasks.
 * Allow the user to set the image version.
 * Device login support.  User doesn't have to create an SPN to actually use the builder.

Closes #3389 
Closes #3456 - per https://github.com/mitchellh/packer/issues/3456#issuecomment-213529225

### CODE REVIEW

**Comment by cbednarski** [comment]
Awesome! I'm looking forward to reviewing this. I may not get to it this week but I will try :)

**Comment by boumenot** [comment]
No worries.  I've included the dependencies with the commit, but they do add quite a bit of bloat to the PR.  I wanted to make sure the CI would succeed, so included them.  (The CI is failing, so I'm working through that too.)  Let me know if you would like me to remove the vendor/ files once I get CI working.

**Comment by cbednarski** [comment]
The vendored files are fine. I will probably do the review locally and ignore that commit.

**Comment by cbednarski** [comment]
I added a close link for https://github.com/mitchellh/packer/issues/3456

**Comment by cbednarski** [comment]
> Device login support. User doesn't have to create an SPN to actually use the builder.

@boumenot do we need to update any of the documentation to reflect this change?

**Comment by boumenot** [comment]
Yes.  I'll take a look at updating the docs with device login information.

**Pull request closed without merging**
