### PR TITLE
[WIP] allow yaml template

### PR DESCRIPTION
**Pull request by vtolstov**
trivial pr for allowing yaml template files.
Now merge now, lacks of testing.

references #1768

### CODE REVIEW

**Comment by vtolstov** [comment]
@mwhooker @rickard-von-essen what do you think?
I'm not include vendored deps for easy reviewing.

**Comment by vtolstov** [comment]
Simple testing convert own json to yml and run validate or build
Converting via
```
ruby -ryaml -rjson -e 'puts YAML.dump(JSON.parse(STDIN.read))' < fedora-25-x86_64.json  > fedora-25-x86_64.yml
```

**Comment by mwhooker** [comment]
hmm, interesting idea. It's not a huge change...

however, I'm not sure I want to touch the file format before 1.0, after which we'll be looking at HCL. Changing it now might make it harder for us in the future.

In the past our recommendation has always been to use a preprocessor: write the packer file in yaml, and then use another tool to write it out as json. This is because we don't want packer to do too many things (part of the [tao](https://www.hashicorp.com/blog/tao-of-hashicorp.html)). I vote no for those reasons, but willing to hear other arguments

**Comment by vtolstov** [comment]
Thanks for review, I don't think that this piece of code hard to maintain. All work mostly doing inside mapstructure.
And I Think that HCL can be added like yaml.

**Comment by cbednarski** [comment]
Hey @vtolstov, my concern here is not necessarily about the code complexity here in the PR, but in config fragmentation in the community. Secondarily I have some concerns about the long tail of code complexity (fix with various formats and such) but I have not given this a lot of thought.

As @mwhooker noted we are planning to add HCL support but we have waited to do this because we want to be able to make a clean cutover to the new format and provide a good way for the communicate to migrate forward, while still maintaining backwards-compatibility.

I realize that YAML and JSON have similar data structures and that _technically_ this change is small, but I don't, for example, want to invest time in documentation or examples in YAML as we are working to move the defaults and examples to HCL. (Existing JSON configs will still be supported.)

This code looks solid and we appreciate your ongoing contributions, but please bear with us while we ship 1.0 and HCL support. I hope that will make writing configs (and comments!) less painful. Thanks!

**Comment by vtolstov** [comment]
How much time needed to get hcl in packer?

**Comment by RichardBronosky** [comment]
Years and years.

**Comment by mwhooker** [comment]
we're waiting for hcl2 to be finalized before putting time into implementing it https://github.com/hashicorp/hcl2 but it is a priority for us

**Comment by vtolstov** [comment]
I think that you hcl2 is dead, because nobody use it. All world uses Yaml and Json for config files and data formats. HCL can be used only in hashicorp. And i don't think that you provide libraries to use hcl from python, ruby , php and other languages.

**Pull request closed without merging**
