### PR TITLE
Allow configurable VNC bind IP for VMware builders

### PR DESCRIPTION
**Pull request by imduffy15**
We were passing a hard coded string of 127.0.0.1 for the VNC bind IP address, we never did fully pass this down into the VMX data.

This PR updates the code to default the bind IP to 127.0.0.1, otherwise taking an option from user configuration.

Signed-off-by: Ian Duffy <ian@ianduffy.ie>

### CODE REVIEW

**Comment by cbednarski** [comment]
Thanks for the PR! The code LGTM! Can you also add a note to the docs so people know they can use this option? Thanks!

**Comment by imduffy15** [comment]
Will do this in the morning (UTC). Thanks Chris.

**Comment by imduffy15** [comment]
Documentation added! Thanks for the quick review @cbednarski

**Comment by cbednarski** [comment]
This is great, thanks!

**Pull request merged**
