### PR TITLE
Auto-determine region and size in digitalocean builder

### PR DESCRIPTION
**Pull request by vtolstov**
Don't write region name and size in builder source, lets try to get it via do api.

Fixes https://github.com/mitchellh/packer/issues/1952

Signed-off-by: Vasiliy Tolstov <v.tolstov@selfip.ru>

### CODE REVIEW

**Comment by sethvargo** [comment]
Hi @vtolstov could you please look into the build failure and rebase?

@ryanuber and @pearkes you've both spent more time in the digital ocean API than myself. Any thoughts?

**Comment by pearkes** [comment]
Their V2 API has the notion of slugs which the promise do not change. I think hardcoding these slugs is a fine solution, as they may re-order or change their API responses and cause users a fair amount of confusion when relying on defaults.

It looks like @vtolstov made a great effort in getting V2 support into Packer for DigitalOcean (#1463), and given that we should be able to use these slugs.

**Comment by vtolstov** [comment]
This patch solve issues, then some region that we have in defaults not avail. So auto determine region imho best of all in this case.
In case of size and promises about slugs... may be i can drop this part. What do you think?

**Comment by pearkes** [comment]
@vtolstov I think that no default is safer then a (potentially) random default as different DO regions have different features, may behave differently and cause confusing bugs.

I say we either choose a new static default region or just remove the default altogether.

**Comment by vtolstov** [comment]
@pearkes ok. i'm remove logic for default size and region.

**Comment by vtolstov** [comment]
@pearkes what do you think now?

**Comment by sethvargo** [comment]
Hey @vtolstov, before Jack does a review, this won't merge cleanly. Could you please rebase?

**Comment by vtolstov** [comment]
@sethvargo thanks, i'm rebase.

**Comment by pearkes** [comment]
@vtolstov Thanks for all your back and forth on this. I think one more thing and we should be good to go.

- I think we should keep the `region_id` backwards compatibility field. We can set region if that is set, but otherwise require it. We don't _need_ to deprecate that now, so I don't think it's worth it for end users.
- Removing the defaults is good. I'll update the changelog to note this for users

Last thing, thanks again for your patience while we figure this out! Kind of a tricky problem!

**Comment by vtolstov** [comment]
@pearkes fixed.

**Comment by mitchellh** [comment]
Thanks! I copied your logic since the merge was broken.

**Pull request closed without merging**
