### PR TITLE
Add parallel gzip compression to the vagrant post-processor

### PR DESCRIPTION
**Pull request by cbednarski**

### CODE REVIEW

**Comment by catsby** [comment]
LGTM :+1: 

Aside, have you benchmarked this?

**Comment by cbednarski** [comment]
@catsby I have not benchmarked it for this case but vtolstov did a benchmark for the original implementation in the compress-post-processor. IIRC the speedup is roughly linear to the number of real CPU cores (not hyper-threads) you have, with some overhead.

**Comment by cbednarski** [comment]
Only anecdotal but my CPUs are not being lazy anymore:

screen shot 2015-08-12 at 13 23 22

**Comment by catsby** [comment]
Excellent :smile:

**Pull request merged**
