### PR TITLE
Add sftp file transfer support

### PR DESCRIPTION
**Pull request by 2opremio**
Adds a new config option: "ssh_file_transfer_method", which can be set to "scp"
or "sftp" (defaults to "scp")

Quoting @mitchellh in https://github.com/mitchellh/packer/issues/1991: "If I saw an SFTP PR though, I'd be happy to merge it." Well, here it is :)

### CODE REVIEW

**Comment by cbednarski** [comment]
Thanks this looks great -- docs, tests, and all! I have not had a chance to review this in detail so I can't promise this will make it into 0.8.3 but I will get to this soonish.

**Comment by 2opremio** [comment]
@cbednarski You're welcome. Let me know if there's anything I can do to get this through.

**Comment by 2opremio** [comment]
Hi @cbednarski . Without meaning to push you, do you have an estimation of when you will be able to merge this? This PR has been here for almost two months now.

**Comment by 2opremio** [comment]
@cbednarski ping

**Comment by 2opremio** [comment]
@cbednarski 6 months and counting, I think this one's going to reach a record :)

**Comment by cbednarski** [comment]
Sorry to keep you waiting so long on this. The PR looks great! I merged this locally to resolve conflicts.

> 6 months and counting, I think this one's going to reach a record :)

(Un)fortunately I don't think we managed to set a record on this one.

Thanks for contributing to packer!

**Pull request merged**
