### PR TITLE
Fixing DigitalOcean documentation urls

### PR DESCRIPTION
**Pull request by ruslansalikhov**
Fixed inserting %5C into links to digitalocean resources.

### CODE REVIEW

**Comment by markpeek** [comment]
Thanks!

**Comment by ideal-knee** [comment]
FYI, these are still broken on the actual page: https://packer.io/docs/builders/digitalocean.html

**Comment by ruslansalikhov** [comment]
Maybe this page still not updated?

**Comment by ideal-knee** [comment]
Yes, I was just surprised the page isn't updated since this change was merged almost 3 months ago.  I just wanted to point it out as it seems like an oversight.

**Pull request merged**
