### PR TITLE
website: force JS/CSS mime-types on deploy

### PR DESCRIPTION
**Pull request by phinze**
Should fix occasional issues with application/octet-stream mime type
assets breaking JS/CSS on site.

### CODE REVIEW

**Comment by cbednarski** [comment]
Hm.. I wonder if we should just remove the `--guess-mime-type` flag form the sync command.

**Comment by cbednarski** [comment]
Thanks for the fix!

**Comment by phinze** [comment]
> Hm.. I wonder if we should just remove the --guess-mime-type flag form the sync command.

It's pretty okay at images / binary files. It's the text heuristics it has trouble with. I think if we dropped it we'd have to manually set mime types on errythang.

**Comment by cbednarski** [comment]
@phinze Yeah that makes sense. It's a shame that feature is not reliable. I've had mixed results with s3cmd's mime detection in the past too. :\

**Pull request merged**
