### PR TITLE
builder/qemu: dont fail on communicator set to none

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@selfip.ru>

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
This will skip provisioners if `"communicator": "none"`. Which is not intended.

**Comment by vtolstov** [comment]
thanks!

**Comment by vtolstov** [comment]
I'm double check this pr, and succeseful build fedora atomic image without any problems.

**Comment by vtolstov** [comment]
@cbednarski ping...

**Comment by vtolstov** [comment]
@cbednarski  @rickard-von-essen does somebody have time to review this?

**Comment by rickard-von-essen** [comment]
LGTM

**Pull request merged**
