### PR TITLE
post-processor/compress: add bgzf compressor

### PR DESCRIPTION
**Pull request by vtolstov**
- Add bgzf compressor support. BGZF allows to seek inside compressed file.
- Also added `format` (string) - Disable archive format autodetection.
- Update `pgzip` to get  sse4 and avx optimizations.

Signed-off-by: Vasiliy Tolstov <v.tolstov@selfip.ru>

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Nice! Could you amend your commit and exclude `vendored` and just include the `Godeps.json`.

**Comment by vtolstov** [comment]
I'm fix pr and pushed force...

**Comment by vtolstov** [comment]
@rickard-von-essen @cbednarski  what next? now tests breaks because of missing deps...

**Comment by rickard-von-essen** [comment]
- Any reason to update `pgzip`?

**Comment by vtolstov** [comment]
Why not?it does not have breaking changes and it have more sse4 and avx
optimizations.
13 Май 2016 г. 10:02 пользователь "Rickard von Essen" <
notifications@github.com> написал:

**Comment by rickard-von-essen** [comment]
OK, I have updated the description of the PR. It's important that it is easy to understand why things changes.

**Comment by rickard-von-essen** [comment]
Thank you for your PR's! 

Sorry for my confusion about `vendor`. It should be included, we changed the contribution guidelines but I forgot that.

Merged via 6a5f6938efae15bc2541c2b9f006005c9775529c

**Comment by vtolstov** [comment]
Thanks!

2016-05-13 13:29 GMT+03:00 Rickard von Essen <notifications@github.com>:

> Thank you for your PR's!
>
> Sorry for my confusion about vendor. It should be included, we changed
> the contribution guidelines but I forgot that.
>
> Merged via 6a5f693
> <https://github.com/mitchellh/packer/commit/6a5f6938efae15bc2541c2b9f006005c9775529c>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/packer/pull/3501#issuecomment-219007846>
>



-- 
Vasiliy Tolstov,
e-mail: v.tolstov@yoctocloud.net

**Comment by cbednarski** [comment]
Looks great, thanks @vtolstov and @rickard-von-essen!

**Pull request closed without merging**
