### PR TITLE
Fix keycodes for ctrl,shift and alt key when sending over VNC

### PR DESCRIPTION
**Pull request by yamamoto-febc**
Hello,

This will fix special keycodes(ctrl,shift and alt) for sending over VNC.

### CODE REVIEW

**Comment by taliesins** [comment]
Can you give a brief description of the problem? Would the requested change simply result in them being aliases of normal key press? So it would not be a key modifier anymore.

So ctrl + c would now be ctrl followed by c.

**Comment by yamamoto-febc** [comment]
It is described in the comments in the following source code.

#### Before apply the requested change
[(/builder/vmware/common/step_type_boot_command.go#L196)](https://github.com/mitchellh/packer/blob/master/builder/vmware/common/step_type_boot_command.go#L196)

```
		if strings.HasPrefix(original, "<leftCtrlOn>") {
			keyCode = special["<leftCtrlOn>"]         // special["<leftCtrlOn>"] is not exists key, so keyCode will set `0`
			original = original[len("<leftCtrlOn>"):]

			c.KeyEvent(keyCode, true)                 // send keydown with keycode '0'
			time.Sleep(time.Second / 10)

			continue
		}
```

#### After apply the requested change

```
		if strings.HasPrefix(original, "<leftCtrlOn>") {
			keyCode = special["<leftCtrl>"]           // special["<leftCtrl>"] is `0xFFE3`
			original = original[len("<leftCtrlOn>"):]

			c.KeyEvent(keyCode, true)                 // send keydown with keycode `0xFFE3`
			time.Sleep(time.Second / 10)

			continue
		}
```

For example, in the case `boot_command` is the following,

```json
"boot_command": [
            "<leftCtrlOn>c<leftCtrlOff>",
        ],
```

It will send following keycodes when before apply the requested change

1. `0`(for `<leftCtlOn>`): key down
1. `0x063`(for `c`): key down
1. `0`(for `<leftCtlOff>`): key up

When  after apply the requested change, It will send following keycodes

2. `0xFFE3`(for `<leftCtlOn>`): key down
2. `0x063`(for `c`): key down
2. `0xFFE3`(for `<leftCtlOff>`): key up

**Comment by taliesins** [comment]
@rickard-von-esson looks good to me.

**Comment by rickard-von-essen** [comment]
Thanks for the explanation. Verified on VMware Fusion.

**Pull request merged**
