### PR TITLE
Re-introduce case sensitive vmx key functionality

### LINKED ISSUE #2574: packer 0.8.3 vmware-iso builder cannot read the virtual machine configuration file
Hi,

with packer 0.8.3 vmware-iso builds failed. I always get  a "cannot read the virtual machine configuration file" and die build stops. 
When i use the 0.8.2 module it works. Any Ideas ?

best regards

Sven

### PR DESCRIPTION
**Pull request by mahcsig**
This is a much narrower focused version of PR #2309 which was reverted in PR #2578 to fix #2574 .

Added two fragment lists, one to handle case sensitive key fragments, another to handle values that cannot be surrounded with quotes. I made them lists so more can be easily added as they are found.

I made them fragment lists, rather than key lists rather than add multiple entries, i.e. : .virtualSSD, rather than scsi0:0.virtualSSD, scsi0:1.virtualSSD, etc.

### CODE REVIEW

**Comment by marc-ta** [comment]
build failures due to unrelated googlecompute compilation errors:

# github.com/mitchellh/packer/builder/googlecompute
builder/googlecompute/driver_gce.go:222: cannot use v (type string) as type *string in field value
?   	github.com/mitchellh/packer/plugin/builder-file	[no test files]
FAIL	github.com/mitchellh/packer/plugin/builder-googlecompute [build failed]

**Comment by dhekimian** [comment]
@mitchellh @cbednarski What's needed to get this merged?

**Comment by cbednarski** [comment]
The previous PR https://github.com/mitchellh/packer/pull/2309 caused a BC break https://github.com/mitchellh/packer/issues/2574 with existing packer configs. I'd like to make sure we have thorough before change / after change testing for this.

**Comment by dandunckelman** [comment]
@cbednarski just rebased against master and the tests are now passing.  Do you think we need more tests?  Thanks

**Comment by dhekimian** [comment]
@mitchellh @cbednarski Please advise as to what else is needed for this to be merged.

**Comment by cbednarski** [comment]
> Do you think we need more tests?

Yes. I'd like tests for some of the example configs that were posted for previous issues. For example:

- https://github.com/mitchellh/packer/issues/2574#issuecomment-129509595
- https://github.com/mitchellh/packer/issues/2574#issuecomment-129581015

I don't mind incorporating this change but it must have tests to verify before / after functionality with at least the failing examples we know about from earlier. Before / after tests allow us to verify A. that we do not break current existing configs when this change is applied and B. that we do not break the virtualSSD option later when we make additional changes to this part of the code.

**Comment by marc-ta** [comment]
Updated and current tests are passing. 

I went to write the new tests, but the issues occurred because of the way the old 
PR was written. This PR doesn't change the process until getting ready to write out the vmx file.
And then it only deviates if the key contains fragments from the "noQuotes" or "caseSensitive" lists, 
which currently only have ".virtualSSD" in them. The test in this PR does cover that, as the 
two original entries are unchanged.

Are there any additional tests that should be created?

**Comment by dhekimian** [comment]
@mitchellh @cbednarski Please advise as to what else is needed for this to be merged.

**Comment by rickard-von-essen** [comment]
Also see #2693

**Comment by marc-ta** [comment]
PR #2707 and PR #2693 achieve the same goal, #2707 uses lists to allow for any future entries that are found to require case sensitivity or require no quotes, but both get SSDs working in VMWare.

Neither removes the entry lower-casing which caused #2309 to fail and be reverted, so that failure won't be repeated.

What can we do to get one of these pulls merged up?

**Comment by dhekimian** [comment]
@cbednarski @mitchellh 

PR #2707 and PR #2693 achieve the same goal, #2707 uses lists to allow for any future entries that are found to require case sensitivity or require no quotes, but both get SSDs working in VMWare.

Neither removes the entry lower-casing which caused #2309 to fail and be reverted, so that failure won't be repeated.

What can we do to get one of these pulls merged up?

**Pull request merged**
