### PR TITLE
Closes #2637 - VRDP support for the virtualbox plugin

### LINKED ISSUE #2637: VRDP support for the virtualbox plugin
Currently if you run packer against virtualbox in headless mode you have no access to debug what happened on the machine and why it might of failed.

Within the VMware driver packer configures and exposes VNC information for connecting directly to the VM.

It would be nice if we did this for VirtualBox too using VRDP

### PR DESCRIPTION
**Pull request by imduffy15**
Signed-off-by: Ian Duffy <ian@ianduffy.ie>

### CODE REVIEW

**Comment by cbednarski** [comment]
Thanks for the PR. This looks great!

Would you be able to [add some docs](https://github.com/mitchellh/packer/blob/master/website/source/docs/builders/virtualbox-iso.html.markdown) for this? At minimum it would be great to mention how to configure `vrdp_port_min` and `vrdp_port_max`.

**Comment by cbednarski** [comment]
Also creating a link to #2637

**Comment by imduffy15** [comment]
Sure no problem @cbednarski, will do this in the morning (UTC time)

**Comment by imduffy15** [comment]
@cbednarski Sorry for the delay, docs have been added as requested.

**Comment by cbednarski** [comment]
Awesome! Thanks for the work you've put into this. I'm excited to use this myself. It will be merged and included with `0.9.0`. Unfortunately I don't have an estimated release day for this release yet.

**Comment by markpeek** [comment]
Agreed this is an awesome feature to add. I will note there is a pending PR #2325 to add putting passwords onto VMware VNC connections. It looks like the VirtualBox VRDP feature might allow for this as well ([link](https://www.virtualbox.org/manual/ch07.html#vbox-auth)). For consistency it might be good to add this functionality or file an issue to track adding this functionality at a later date.

**Comment by imduffy15** [comment]
Hey @markpeek 

I've implemented the password feature.... I'll update this PR.

However it is important to note that it doesn't work, this appears to be due to a known issue with virtualbox and the "External" authentication

https://www.virtualbox.org/ticket/4406

**Pull request closed without merging**
