### PR TITLE
builder/openstack: Support using SSH password.

### PR DESCRIPTION
**Pull request by rickard-von-essen**
This adds support for using `ssh_password` to connect to a OpenStack
instance. If `ssh_password` is defined creation of the temporary key pair
is skipped.

_This is not tested at all! It just compiles. I'll remove WIP when I hade some time to test this._

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Closes #3930

**Comment by rickard-von-essen** [comment]
Completed some test. This works with any of _temporary keypairs_, `ssh_private_key_file`, and `ssh_password`.

**Comment by mwhooker** [comment]
👍

**Comment by rguruju** [comment]
👍 Looks good, thank you.

**Pull request merged**
