### PR TITLE
Docker: Refactor communicator to use API

### LINKED ISSUE #3102: docker builder fails to copy from `uploadData` when running in nested container. hangs forever
Had this problem with 0.8.6-release, so did researching and building v0.8.7.dev (b7ba9a5) and getting same issue -

when building from within a docker container...  _who is connecting to the parent docker daemon via exposed unix socket

os is debian jessie, building an ubuntu foundation image from ubuntu:latest

problem is with inline and shell provisioner. haven't got as far as ansible_local provisioner yet, but i imagine that is the same issue.....

the invocation of the container at runtime for which packer is running under looks like this:

```
docker run -P -d --privileged -it  -v /lib/x86_64-linux-gnu/libdevmapper.so.1.02.1:/lib/x86_64-linux-gnu/libdevmapper.so.1.02.1 -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker docker2.moammo.net:5000/jenkins-exp:0.2 
```

the official jenkinsci docker image is a parent of docker2.moammo.net:5000/jenkins-exp:0.2

from the top of my packer builder.json

```
{
  "variables": {
    "imageTag": "",
    "imageRepo": ""
  },
  "builders": [
    {
      "type": "docker",
      "image": "ubuntu:latest",
      "commit": true,
      "run_command": [
        "-ti",
        "-v",
        "/tmp/packerfiles:/tmp/packerfiles",
        "-d",
        "{{.Image}}",
        "/bin/bash",
        "--noprofile",
        "--norc"
      ]
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "scripts": [
        "packer/scripts/docker_ubuntu.sh"
      ]
    },
```

my packer invocation looks like this:

```
VERSION=$1
IMGREPO=$2
JSONFILE=$3
mkdir -p /tmp/packerfiles
TMPDIR=/tmp/packerfiles PACKER_LOG=1 packer build \
  -var imageTag=${VERSION} \
  -var imageRepo=${IMGREPO} \
  packer/scripts/${JSONFILE}.json
exit $?
```

output from PACKER_LOG=1

```
2016/01/22 18:45:44 ui: �[1;32m==> docker: Starting docker container...�[0m
2016/01/22 18:45:44 ui: �[0;32m    docker: Run command: docker run -v /var/jenkins_home/.packer.d/tmp/packer-docker523294758:/packer-files -ti -v /tmp/packerfiles:/tmp/packerfiles -d ubuntu:latest /bin/bash --noprofile --norc�[0m
�[0;32m    docker: Status: Image is up to date for ubuntu:latest�[0m
�[1;32m==> docker: Starting docker container...�[0m
2016/01/22 18:45:44 packer: 2016/01/22 18:45:44 Starting container with args: [run -v /var/jenkins_home/.packer.d/tmp/packer-docker523294758:/packer-files -ti -v /tmp/packerfiles:/tmp/packerfiles -d ubuntu:latest /bin/bash --noprofile --norc]
�[0;32m    docker: Run command: docker run -v /var/jenkins_home/.packer.d/tmp/packer-docker523294758:/packer-files -ti -v /tmp/packerfiles:/tmp/packerfiles -d ubuntu:latest /bin/bash --noprofile --norc�[0m
2016/01/22 18:45:44 packer: 2016/01/22 18:45:44 Waiting for container to finish starting
2016/01/22 18:45:47 ui: �[0;32m    docker: Container ID: 6a9448c9580ac223dc4b8e5dbc7e174cc888293bf814e254cafe09c99dfe2570�[0m
�[0;32m    docker: Container ID: 6a9448c9580ac223dc4b8e5dbc7e174cc888293bf814e254cafe09c99dfe2570�[0m
2016/01/22 18:45:47 packer: 2016/01/22 18:45:47 Running the provision hook
2016/01/22 18:45:47 ui: �[1;32m==> docker: Provisioning with shell script: packer/scripts/docker_ubuntu.sh�[0m
2016/01/22 18:45:47 packer: 2016/01/22 18:45:47 Opening packer/scripts/docker_ubuntu.sh for reading
�[1;32m==> docker: Provisioning with shell script: packer/scripts/docker_ubuntu.sh�[0m
2016/01/22 18:45:47 packer: 2016/01/22 18:45:47 [INFO] 1035 bytes written for 'uploadData'
2016/01/22 18:45:47 [INFO] 1035 bytes written for 'uploadData'
2016/01/22 18:45:47 packer: 2016/01/22 18:45:47 Executing in container 6a9448c9580ac223dc4b8e5dbc7e174cc888293bf814e254cafe09c99dfe2570: "(command cp /packer-files/upload507966797 /tmp/script_898.sh) >/packer-files/cmd213455432 2>&1; echo $? >/packer-files/cmd213455432-exit"
2016/01/22 18:45:49 packer: 2016/01/22 18:45:49 Waiting for exit code to appear for remote command...
```

I enter the container and inspect /packer-files

```
root@docker3:~# docker exec -it big_kilby /bin/bash
root@6a9448c9580a:/# pushd /tmp/packerfiles/
/tmp/packerfiles /
root@6a9448c9580a:/tmp/packerfiles# ls -lah
total 16K
drwxr-xr-x 4 root root 4.0K Jan 22 18:35 .
drwxrwxrwt 3 root root 4.0K Jan 22 18:45 ..
drwxr-xr-x 2 root root 4.0K Jan 22 18:35 packer-docker329986877
drwxr-xr-x 2 root root 4.0K Jan 22 16:50 packer-docker463191192
root@6a9448c9580a:/tmp/packerfiles# cat packer-docker329986877/cmd749252215
cmd749252215       cmd749252215-exit
root@6a9448c9580a:/tmp/packerfiles# cat packer-docker329986877/cmd749252215*
cp: cannot stat '/packer-files/upload772259704': No such file or directory
1
root@6a9448c9580a:/tmp/packerfiles# pushd /packer-files/; ls -lah
/packer-files /tmp/packerfiles /
total 16K
drwxr-xr-x  2 root root 4.0K Jan 22 18:45 .
drwxr-xr-x 22 root root 4.0K Jan 22 18:45 ..
-rw-r--r--  1 root root   75 Jan 22 18:45 cmd213455432
-rw-r--r--  1 root root    2 Jan 22 18:45 cmd213455432-exit
root@6a9448c9580a:/packer-files# cat cmd213455432*
cp: cannot stat '/packer-files/upload507966797': No such file or directory
1
```

### PR DESCRIPTION
**Pull request by vancluever**
This PR now covers the whole communicator - the whole thing has been re-factored to use the Docker API, via `go-dockerclient`. Also, seeing as this removes the need for a shared volume between the host and container, I've removed that code as well. Deps have been vendored in a separate commit.

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
I have rewritten the docker driver to use the api instead of the cli. I haven't yet fixed the communicator in the same way. I'll put up a WIP PR today.

**Comment by vancluever** [comment]
@rickard-von-essen good to know! Are you planning on doing the communicator or would you like some help on that? Not too sure if you mean that this work is done already (or was in the process of being done).

**Comment by rickard-von-essen** [comment]
I haven't rewritten the docker communicationor yet. I wouldn't mind help doing but ping me If you start so we don't do overlapping  work.

**Comment by rickard-von-essen** [comment]
This seems to include a bit to much vendor updates.

**Comment by rickard-von-essen** [comment]
Related to #3921

**Comment by vancluever** [comment]
@rickard-von-essen do you know what deps are not needed? These were all processed with `govendor add +external`.

**Comment by vancluever** [comment]
PS: I'm adding the final communicator bits shortly.

**Comment by vancluever** [comment]
I've re-based this,  so that all of the communicator and vendor updates are in 2 commits versus than 4.

I also took a look at the temporary directory that was created to interface with the communicator before and I think we could probably get rid of it - will submit that in a separate commit.

**Comment by vancluever** [comment]
All done and tempdir code removed. Removing WIP tag now, this is good to review!

**Comment by rickard-von-essen** [comment]
> These were all processed with `govendor add +external`.

Ok, we use [godep](https://github.com/tools/godep) to handle vendoring, not _govendor_ that's why it looks wrong. Could you drop your second commit and add a new one where you use godep to add deps, see [CONTRIBUTING.md](https://github.com/mitchellh/packer/blob/master/CONTRIBUTING.md#godeps)

**Comment by vancluever** [comment]
Gotcha, didn't know that Packer didn't move to `govendor`!

I've re-added the deps. Seemed to be a very large changeset when `godep save ./...` was done (after a `godep restore`, adding `go-dockerclient` and cycling through the rest when they were reported), I'm not too sure if it broke anything. It builds on my side (Linux) but looks like the windows build failed.

I'm going to be out for most of the weekend so I won't be able to mess around with the deps any more for a couple of days, but if you guys can fix this feel free to cherry-pick the commits and fix up the deps. Otherwise I'll look into it more when I get back.

**Comment by vancluever** [comment]
I've just removed the deps. Something is obviously wrong - I'm just going to leave it at the 2 commits here for now. Feel free to drop in the deps if you guys can get it going over the weekend.

**Comment by rickard-von-essen** [comment]
Why are you using `github.com/fsouza/go-dockerclient` in favour of `github.com/docker/docker/client`? Any particular reason?

**Comment by vancluever** [comment]
The main reason is that the the package that was referred to in #3102. But it does seem to be better documented. Looking at the GoDoc for that package versus go-dockerclient, if I didn't start with the latter, I probably would have had a much rougher of a time trying to figure out exactly what needed to happen. https://godoc.org/github.com/docker/docker/client#Client.CopyFromContainer for instance does not include much information about what one needs to do with the I/O stream, while https://godoc.org/github.com/fsouza/go-dockerclient#Client.DownloadFromContainer is clearer on what exactly it does, and even includes a link to the REST API call.

It seems like a bit of a cleaner API too, but that could be subjective.

**Comment by rickard-von-essen** [comment]
Ok good to know. And yes the documentation for `docker/client` was non-existing. I hade to read the source.

**Comment by vancluever** [comment]
Not too sure how this closed itself, I was just pushing updated deps. I am going to re-open this PR under a different branch name and reference back to this.

**Pull request closed without merging**
