### PR TITLE
Remove duplicate permission

### PR DESCRIPTION
**Pull request by sysadmiral**
***Documentation improvement***

In the suggested policy `ec2:CopyImage` was listed twice.

I've also sorted alphabetically to make it easier for somebody who might be recreating the policy in the AWS gui to follow along more easily.

### CODE REVIEW

**Comment by mwhooker** [comment]
thanks!

**Comment by sysadmiral** [comment]
It looks like this change was reverted and then reapplied in a slightly different (broken) way. Is there any reason for that?

**Comment by rickard-von-essen** [comment]
Could you describe what is wrong? Quickly looking I see a trailing , is there anything more?

**Comment by mwhooker** [comment]
the original PR elided a crucial permission, so reverted to master and
applied the deduplication again with a sort -u. must have forgotten the
commas. It should be fixed now in master

**Comment by sysadmiral** [comment]
sweet!

**Pull request merged**
