### PR TITLE
Docker: Refactor communicator to use API

### PR DESCRIPTION
**Pull request by vancluever**
Ref: #3917 - re-opening here as that one was accidentally closed.

Godeps updated manually, used `govendor fetch github.com/fsouza/go-dockerclient` to fetch the outstanding deps and then manually updated `Godeps/Godeps.json`. `golang.org/x/sys/windows` was required so `golang.org/x/sys/unix` needed updating too, but other than that pretty sure all of the others are required by `go-dockerclient` as downstream deps.

Verified that `godep restore` works with this changeset.

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Godep don't add `_test.go` files.

**Comment by rickard-von-essen** [comment]
Related to #3921

**Comment by vancluever** [comment]
OK, I removed all test files (git show --name-only | grep _test.go | xargs rm) and re-pushed. Does it look okay now? Tests still seem to check out and the binary builds.

**Comment by mwhooker** [comment]
hopefully will resolve #3642

**Comment by rickard-von-essen** [comment]
@vancluever Now we switched to `govendor` ;-) and I'm conviced that `go-dockerclient` is way simpler than the official go docker client.

**Comment by vancluever** [comment]
@rickard-von-essen Amazing I'll update the PR with a fresh master and the deps re-vendored under `govendor`. PS: If you need help with #3921 let me know - willing to help get it out the door!

**Comment by rickard-von-essen** [comment]
If you have some time to dig into #3921 it would be awesome. I won't have much time to spend on it before 0.12.0 at least (planned for 5 nov). I would like to switch to go-dockerclient. If you would like you can patch on whatever work I've done to this on a new branch and open a new PR. I can push commits to that.

**Comment by vancluever** [comment]
Great @rickard-von-essen, I'll get on it sometime this weekend probably :)

**Comment by mwhooker** [comment]
Going to close this so we can focus on #4186

**Pull request closed without merging**
