### PR TITLE
Fix digitalocean provider for private images [fixes mitchellh/packer#1792]

### PR DESCRIPTION
**Pull request by mojotalantikite**
This fixes an issue with private images on Digital Ocean, which is discussed in #1792. Opening a PR as it was requested in the thread.

### CODE REVIEW

**Comment by dietervds** [comment]
Could really use this merge, have been stuck on this for a while :)

**Comment by vtolstov** [comment]
@sethvargo ping...

**Comment by boris317** [comment]
This is a bit of a blocker for me too. I've fixed it locally for now.

**Comment by dietervds** [comment]
@boris317: Can I ask how you fixed it locally? I'd love to try the same.

**Comment by boris317** [comment]
@dietervds I built and installed packer from source. Making sure to apply this change (d174ffe1fa) referenced in this pull request first

**Comment by dietervds** [comment]
Might have to resort to that as well :) Thanks!

**Comment by mitchellh** [comment]
LGTM! Thanks!

**Pull request merged**
