### PR TITLE
GCE builder: Switch to google.DefaultClient

### PR DESCRIPTION
**Pull request by gottwald**
The use of google.DefaultClient makes a series of authentication mechanisms possible.

See the code comment for the mech precedence.

Most important addition: Authentication through an already authenticated gcloud command.
Every GCE user has this, so there is no need to create service accounts any more or share keys.

### CODE REVIEW

**Comment by gottwald** [comment]
Ping. Is there anything I can do to get this merged in the near future?

**Comment by rickard-von-essen** [comment]
Sorry for the delay can you update the docs with the comments from the code.

**Comment by gottwald** [comment]
Added documentation. WDYT?

**Comment by rickard-von-essen** [comment]
LGTM

**Pull request merged**
