### PR TITLE
Additional disks for vmware iso

### PR DESCRIPTION
**Pull request by sneal**
#930, but with master merged into it.

### CODE REVIEW

**Comment by eperdeme** [comment]
Just compiled this locally and deployed to Linux64 using VMWare player 6 and appears to work beautifully. Glad this is here as it would be stumped without the 2nd disk.

Looking forward to the merge so I can update easier :+1:

**Comment by kkinnear** [comment]
We too have been using this in a locally built version, and it works well, but it would sure be nice if it finally made it to the standard released version.  Trying to keep our locally built version up to date with other fixes and capabilities is a losing proposition -- it would be great to just be able to use the standard release. 

In a summary of issues, this one says that it needs documentation, but it looks like sneal did the documentation on Sept 15, 2014.  Don't know why it still says "needs documentation".

Anyway, if there is any way to get this into a released version it would be *great*!  Thanks!

**Comment by ostap36** [comment]
Hello, any chance this can be added to 0.8 release? Thank you

**Comment by dhekimian** [comment]
@sethvargo @sneal What's necessary to get this merged? 

I'd be willing to help but not sure what's holding this up. It would be extremely useful for multiple of our use cases that are keeping us from building all our VMs with Packer.

**Comment by sneal** [comment]
@sethvargo Rebased this so it'll merge cleanly, but it appears there's some additional work to do once I setup my Go dev environment again.

**Comment by kkinnear** [comment]
Folks -- thanks very much for pushing this forward.  Two disk support remains a requirement for
our use case, and we are running a local build of packer with this capability included -- with
all of the problems that come along with that.

Again, many thanks for working on this so we can use the regular packer releases!

Kim

**Comment by sneal** [comment]
WOMM with an older Ubuntu 12.04 build and VMWare Fusion 7.1.

Added this to my packer.json config
```
"additionaldisk_size": [10140],
```

Added this to my preseed.cfg
```
d-i partman-auto/disk string /dev/sda
```

Output, look for `Creating additional hard drives...`
```
~/vagrant_basebox/ubuntu1204: packer build -only=vmware-iso packer.json
vmware-iso output will be in this color.

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: http://releases.ubuntu.com/12.04/ubuntu-12.04.5-server-amd64.iso
==> vmware-iso: Creating virtual machine disk
==> vmware-iso: Creating additional hard drives...
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Starting HTTP server on port 8205
==> vmware-iso: Starting virtual machine...
==> vmware-iso: Waiting 10s for boot...
==> vmware-iso: Connecting to VM via VNC
==> vmware-iso: Typing the boot command over VNC...
==> vmware-iso: Waiting for SSH to become available...
==> vmware-iso: Connected to SSH!
==> vmware-iso: Uploading the 'linux' VMware Tools
==> vmware-iso: Provisioning with shell script: ../../scripts/update.sh
    vmware-iso: [sudo] password for vagrant: ==> Clearing out apt list cache
    vmware-iso: ==> Updating list of repositories
    vmware-iso: Get:1 http://us.archive.ubuntu.com precise Release.gpg [198 B]
...
```

**Comment by mitchellh** [comment]
LGTM!

**Pull request merged**
