### PR TITLE
provisioner/shell: randomize default script name

### LINKED ISSUE #1872: Remote file disappears during shell provision run
We are using packer (0.7.5) with a windows guest (Win2012r2) running on aws (using the amazon-ebs builder).

We are using the [packer windows](https://github.com/joefitzgerald/packer-windows) approach, installing openssh during first boot, then doing the rest of the provisioning run via packer provisioners after that.

For the last few days, I've been fighting with issues when executing a shell provisioner, similar to:

```json
{
    "type": "shell",
    "remote_path": "/tmp/script.bat",
    "binary": true,
    "execute_command": "{{.Vars}} cmd /c C:/Windows/Temp/script.bat",
    "scripts": [
      "./scripts/vagrant-ssh.bat",
      "./scripts/enable-rdp.bat",
      "./scripts/chef.bat",
      "./scripts/win-updates.bat"
    ]
  }
```

Randomly, we are getting an error ` The batch file cannot be found.` when the batch file executes a child command. It appears (after investigation using the -debug flag and using procmon) that the file is getting deleted somehow. 

This doesn't always happen in the same spot, but does always appear after running a child command (eg, powershell), and that exits and returns to flow of execution to the calling batch file.

When this happens (and packer pauses before tearing it down), if I look in the temp folder, the batch file does not exist. (OpenSSH symlinks /tmp/ to c:\windows\temp).

The child command is returning a 0 error code.

I've spent a few hours poring over the code, and even though I'm no golang programmer, I cant find anywhere that this might be happening.

Can anyone suggest further avenues to investigate?

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #1872 

Randomize the name to help fight against weird non-determinism in Windows delete/create ordering of files.

### CODE REVIEW

**Comment by cbednarski** [comment]
Weird bug! LGTM

**Comment by sethvargo** [comment]
Do you think we should use some kind of global counter instead?

**Comment by cbednarski** [comment]
@sethvargo We could use a hash or UUID for increased randomness / reduced chance of collision. It doesn't seem to need autoinc functionality though, and should remain stateless between packer runs.

**Comment by mitchellh** [comment]
@sethvargo I agree with @cbednarski. Plus, with the other recent change in Packer, this script is removed after reach run, and all of Packer's resources are ephemeral anyways, so I actually think random is better than content hashing.

**Pull request merged**
